import { RoommateProfile } from '../types/models';

export const additionalProfiles: RoommateProfile[] = [
  {
    id: '27',
    name: 'Kendall Collins',
    age: 28,
    zodiacSign: 'Libra',
    gender: 'female',
    bio: 'Laid-back pharmacist into wine tasting and dancing. Prefer a quiet home with occasional social hangouts.',
    occupation: 'Pharmacist',
    budget: 2100,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=270',
      'https://picsum.photos/400/500?random=271',
      'https://picsum.photos/400/500?random=272',
      'https://picsum.photos/400/500?random=273',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 4,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'DUMBO',
      moveInDate: '06/17/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 74,
  },
  {
    id: '28',
    name: 'Grace Phillips',
    age: 33,
    zodiacSign: 'Taurus',
    gender: 'male',
    bio: 'Creative product manager seeking a friendly roommate. Enjoy thrifting, cycling, and weekend adventures.',
    occupation: 'Product Manager',
    budget: 1300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=280',
      'https://picsum.photos/400/500?random=281',
      'https://picsum.photos/400/500?random=282',
      'https://picsum.photos/400/500?random=283',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 4,
      workSchedule: 'Flexible',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'Williamsburg',
      moveInDate: '04/02/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 91,
  },
  {
    id: '29',
    name: 'Sebastian Russell',
    age: 29,
    zodiacSign: 'Capricorn',
    gender: 'other',
    bio: 'Civil Engineer who enjoys kayaking and martial arts. Looking for a chill and respectful roommate.',
    occupation: 'Civil Engineer',
    budget: 2300,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=290',
      'https://picsum.photos/400/500?random=291',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Upper East Side',
      moveInDate: '01/04/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 84,
  },
  {
    id: '30',
    name: 'Quinn Carter',
    age: 25,
    zodiacSign: 'Virgo',
    gender: 'male',
    bio: 'Passionate mechanical engineer looking for a like-minded roommate. Into basketball and yoga.',
    occupation: 'Mechanical Engineer',
    budget: 1400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=300',
      'https://picsum.photos/400/500?random=301',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'Brooklyn Heights',
      moveInDate: '03/03/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 62,
  },
  {
    id: '31',
    name: 'Gabriel Gutierrez',
    age: 32,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Working as a entrepreneur. Love hiking, running, and trying new restaurants. Tidy and considerate.',
    occupation: 'Entrepreneur',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=310',
      'https://picsum.photos/400/500?random=311',
      'https://picsum.photos/400/500?random=312',
      'https://picsum.photos/400/500?random=313',
      'https://picsum.photos/400/500?random=314',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 8,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'SoHo',
      moveInDate: '01/05/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 82,
  },
  {
    id: '32',
    name: 'Riley Perry',
    age: 32,
    zodiacSign: 'Aquarius',
    gender: 'male',
    bio: 'Passionate consultant looking for a like-minded roommate. Into cooking and podcasts.',
    occupation: 'Consultant',
    budget: 2200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=320',
      'https://picsum.photos/400/500?random=321',
      'https://picsum.photos/400/500?random=322',
      'https://picsum.photos/400/500?random=323',
      'https://picsum.photos/400/500?random=324',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 5,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Midtown',
      moveInDate: '06/12/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 89,
  },
  {
    id: '33',
    name: 'Lucas Thomas',
    age: 32,
    zodiacSign: 'Gemini',
    gender: 'male',
    bio: 'Project Manager by day, kayaking enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Project Manager',
    budget: 1700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=330',
      'https://picsum.photos/400/500?random=331',
      'https://picsum.photos/400/500?random=332',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 4,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Bedford-Stuyvesant',
      moveInDate: '02/26/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 66,
  },
  {
    id: '34',
    name: 'Mason Campbell',
    age: 27,
    zodiacSign: 'Libra',
    gender: 'male',
    bio: 'Ambitious financial analyst who values work-life balance. Enjoy music and wine tasting on weekends.',
    occupation: 'Financial Analyst',
    budget: 700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=340',
      'https://picsum.photos/400/500?random=341',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 3,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Greenpoint',
      moveInDate: '06/20/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 86,
  },
  {
    id: '35',
    name: 'Riley Kim',
    age: 33,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Creative urban planner seeking a friendly roommate. Enjoy board games, live music, and weekend adventures.',
    occupation: 'Urban Planner',
    budget: 2100,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=350',
      'https://picsum.photos/400/500?random=351',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 4,
      workSchedule: 'Student',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Long Island City',
      moveInDate: '02/08/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 84,
  },
  {
    id: '36',
    name: 'Scarlett Turner',
    age: 29,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Startup Founder by day, board games enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Startup Founder',
    budget: 2300,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=360',
      'https://picsum.photos/400/500?random=361',
      'https://picsum.photos/400/500?random=362',
      'https://picsum.photos/400/500?random=363',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 8,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'East Williamsburg',
      moveInDate: '05/15/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 60,
  },
  {
    id: '37',
    name: 'Kai Gray',
    age: 24,
    zodiacSign: 'Capricorn',
    gender: 'female',
    bio: 'Passionate insurance agent looking for a like-minded roommate. Into pottery and gaming.',
    occupation: 'Insurance Agent',
    budget: 1300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=370',
      'https://picsum.photos/400/500?random=371',
      'https://picsum.photos/400/500?random=372',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Bedford-Stuyvesant',
      moveInDate: '02/10/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 84,
  },
  {
    id: '38',
    name: 'Carter Martinez',
    age: 29,
    zodiacSign: 'Scorpio',
    gender: 'female',
    bio: 'Lawyer with a passion for pottery. Also love basketball. Looking for a compatible living situation.',
    occupation: 'Lawyer',
    budget: 800,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=380',
      'https://picsum.photos/400/500?random=381',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 6,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Park Slope',
      moveInDate: '01/25/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 76,
  },
  {
    id: '39',
    name: 'Violet Gutierrez',
    age: 22,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Insurance Agent by day, running enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Insurance Agent',
    budget: 700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=390',
      'https://picsum.photos/400/500?random=391',
      'https://picsum.photos/400/500?random=392',
      'https://picsum.photos/400/500?random=393',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 3,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Hollywood',
      moveInDate: '02/17/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 89,
  },
  {
    id: '40',
    name: 'Morgan Gomez',
    age: 33,
    zodiacSign: 'Libra',
    gender: 'male',
    bio: 'Friendly graphic designer seeking a tidy roommate. Big fan of baking and meditation.',
    occupation: 'Graphic Designer',
    budget: 2200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=400',
      'https://picsum.photos/400/500?random=401',
      'https://picsum.photos/400/500?random=402',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 4,
      workSchedule: 'Flexible',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'Santa Monica',
      moveInDate: '01/23/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 61,
  },
  {
    id: '41',
    name: 'Layla Robinson',
    age: 33,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Passionate product manager looking for a like-minded roommate. Into basketball and traveling.',
    occupation: 'Product Manager',
    budget: 1000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=410',
      'https://picsum.photos/400/500?random=411',
      'https://picsum.photos/400/500?random=412',
      'https://picsum.photos/400/500?random=413',
      'https://picsum.photos/400/500?random=414',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 4,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Arts District',
      moveInDate: '06/04/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 77,
  },
  {
    id: '42',
    name: 'Kai White',
    age: 34,
    zodiacSign: 'Cancer',
    gender: 'male',
    bio: 'Friendly barista seeking a tidy roommate. Big fan of rock climbing and baking.',
    occupation: 'Barista',
    budget: 1900,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=420',
      'https://picsum.photos/400/500?random=421',
      'https://picsum.photos/400/500?random=422',
      'https://picsum.photos/400/500?random=423',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 8,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'West Hollywood',
      moveInDate: '03/17/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 70,
  },
  {
    id: '43',
    name: 'Sebastian Nelson',
    age: 22,
    zodiacSign: 'Leo',
    gender: 'female',
    bio: 'Ambitious photographer who values work-life balance. Enjoy running and basketball on weekends.',
    occupation: 'Photographer',
    budget: 2000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=430',
      'https://picsum.photos/400/500?random=431',
      'https://picsum.photos/400/500?random=432',
      'https://picsum.photos/400/500?random=433',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Hollywood',
      moveInDate: '02/19/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 88,
  },
  {
    id: '44',
    name: 'Charlotte Jimenez',
    age: 21,
    zodiacSign: 'Leo',
    gender: 'female',
    bio: 'Civil Engineer who enjoys skateboarding and dancing. Looking for a chill and respectful roommate.',
    occupation: 'Civil Engineer',
    budget: 2200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=440',
      'https://picsum.photos/400/500?random=441',
      'https://picsum.photos/400/500?random=442',
      'https://picsum.photos/400/500?random=443',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 3,
      workSchedule: 'Student',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Santa Monica',
      moveInDate: '03/08/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 84,
  },
  {
    id: '45',
    name: 'Aiden Martinez',
    age: 32,
    zodiacSign: 'Aquarius',
    gender: 'female',
    bio: 'Creative musician seeking a friendly roommate. Enjoy swimming, music, and weekend adventures.',
    occupation: 'Musician',
    budget: 1000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=450',
      'https://picsum.photos/400/500?random=451',
      'https://picsum.photos/400/500?random=452',
      'https://picsum.photos/400/500?random=453',
      'https://picsum.photos/400/500?random=454',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 6,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Silver Lake',
      moveInDate: '02/13/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'instagram' },
    },
    compatibility: 77,
  },
  {
    id: '46',
    name: 'Mia Adams',
    age: 23,
    zodiacSign: 'Capricorn',
    gender: 'female',
    bio: 'Ambitious architect who values work-life balance. Enjoy photography and traveling on weekends.',
    occupation: 'Architect',
    budget: 1500,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=460',
      'https://picsum.photos/400/500?random=461',
      'https://picsum.photos/400/500?random=462',
      'https://picsum.photos/400/500?random=463',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 5,
      workSchedule: 'Flexible',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Silver Lake',
      moveInDate: '05/20/2025',
      bedrooms: 2,
    },
    compatibility: 72,
  },
  {
    id: '47',
    name: 'Chloe Fisher',
    age: 32,
    zodiacSign: 'Virgo',
    gender: 'male',
    bio: 'Journalist who loves tennis. Looking for someone respectful, clean, and open to writing together.',
    occupation: 'Journalist',
    budget: 2300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=470',
      'https://picsum.photos/400/500?random=471',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'West Hollywood',
      moveInDate: '05/11/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 68,
  },
  {
    id: '48',
    name: 'Wyatt James',
    age: 34,
    zodiacSign: 'Capricorn',
    gender: 'other',
    bio: 'Product Manager with a passion for rock climbing. Also love thrifting. Looking for a compatible living situation.',
    occupation: 'Product Manager',
    budget: 1000,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=480',
      'https://picsum.photos/400/500?random=481',
      'https://picsum.photos/400/500?random=482',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 3,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Silver Lake',
      moveInDate: '04/13/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 93,
  },
  {
    id: '49',
    name: 'Henry Nguyen',
    age: 28,
    zodiacSign: 'Capricorn',
    gender: 'female',
    bio: 'Ambitious consultant who values work-life balance. Enjoy basketball and skateboarding on weekends.',
    occupation: 'Consultant',
    budget: 2300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=490',
      'https://picsum.photos/400/500?random=491',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 3,
      workSchedule: 'Student',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Venice',
      moveInDate: '05/19/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 64,
  },
  {
    id: '50',
    name: 'Evelyn Edwards',
    age: 23,
    zodiacSign: 'Gemini',
    gender: 'female',
    bio: 'Passionate art director looking for a like-minded roommate. Into rock climbing and skateboarding.',
    occupation: 'Art Director',
    budget: 1100,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=500',
      'https://picsum.photos/400/500?random=501',
      'https://picsum.photos/400/500?random=502',
      'https://picsum.photos/400/500?random=503',
      'https://picsum.photos/400/500?random=504',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 3,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'West Loop',
      moveInDate: '04/25/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 76,
  },
  {
    id: '51',
    name: 'Aiden Collins',
    age: 24,
    zodiacSign: 'Cancer',
    gender: 'male',
    bio: 'Laid-back barista into traveling and pottery. Prefer a quiet home with occasional social hangouts.',
    occupation: 'Barista',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=510',
      'https://picsum.photos/400/500?random=511',
      'https://picsum.photos/400/500?random=512',
      'https://picsum.photos/400/500?random=513',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Logan Square',
      moveInDate: '05/06/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'instagram' },
    },
    compatibility: 74,
  },
  {
    id: '52',
    name: 'Penelope Simmons',
    age: 31,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Working as a data analyst. Love swimming, cooking, and trying new restaurants. Tidy and considerate.',
    occupation: 'Data Analyst',
    budget: 1500,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=520',
      'https://picsum.photos/400/500?random=521',
      'https://picsum.photos/400/500?random=522',
      'https://picsum.photos/400/500?random=523',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 9,
      workSchedule: 'Hybrid',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'River North',
      moveInDate: '01/20/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 84,
  },
  {
    id: '53',
    name: 'Jordan Ward',
    age: 22,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Working as a project manager. Love thrifting, wine tasting, and trying new restaurants. Tidy and considerate.',
    occupation: 'Project Manager',
    budget: 1300,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=530',
      'https://picsum.photos/400/500?random=531',
      'https://picsum.photos/400/500?random=532',
      'https://picsum.photos/400/500?random=533',
      'https://picsum.photos/400/500?random=534',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 6,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Lincoln Park',
      moveInDate: '04/15/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'instagram' },
    },
    compatibility: 82,
  },
  {
    id: '54',
    name: 'Layla Powell',
    age: 26,
    zodiacSign: 'Aquarius',
    gender: 'male',
    bio: 'Research Scientist by day, wine tasting enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Research Scientist',
    budget: 2400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=540',
      'https://picsum.photos/400/500?random=541',
      'https://picsum.photos/400/500?random=542',
      'https://picsum.photos/400/500?random=543',
      'https://picsum.photos/400/500?random=544',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Wicker Park',
      moveInDate: '04/19/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'instagram' },
    },
    compatibility: 84,
  },
  {
    id: '55',
    name: 'Morgan Henderson',
    age: 31,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Friendly data analyst seeking a tidy roommate. Big fan of gaming and traveling.',
    occupation: 'Data Analyst',
    budget: 2200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=550',
      'https://picsum.photos/400/500?random=551',
      'https://picsum.photos/400/500?random=552',
      'https://picsum.photos/400/500?random=553',
      'https://picsum.photos/400/500?random=554',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Student',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Lakeview',
      moveInDate: '05/01/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 65,
  },
  {
    id: '56',
    name: 'Scarlett Barnes',
    age: 29,
    zodiacSign: 'Leo',
    gender: 'female',
    bio: 'Real Estate Agent with a passion for cooking. Also love gardening. Looking for a compatible living situation.',
    occupation: 'Real Estate Agent',
    budget: 2100,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=560',
      'https://picsum.photos/400/500?random=561',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Logan Square',
      moveInDate: '06/18/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 92,
  },
  {
    id: '57',
    name: 'Gabriel Allen',
    age: 22,
    zodiacSign: 'Cancer',
    gender: 'male',
    bio: 'Laid-back insurance agent into running and surfing. Prefer a quiet home with occasional social hangouts.',
    occupation: 'Insurance Agent',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=570',
      'https://picsum.photos/400/500?random=571',
      'https://picsum.photos/400/500?random=572',
      'https://picsum.photos/400/500?random=573',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 6,
      workSchedule: 'Freelance',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Wicker Park',
      moveInDate: '05/21/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 88,
  },
  {
    id: '58',
    name: 'Finley Bell',
    age: 24,
    zodiacSign: 'Aquarius',
    gender: 'male',
    bio: 'Event Planner by day, pottery enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Event Planner',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=580',
      'https://picsum.photos/400/500?random=581',
      'https://picsum.photos/400/500?random=582',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 8,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Logan Square',
      moveInDate: '04/04/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 91,
  },
  {
    id: '59',
    name: 'Blair Harris',
    age: 29,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Art Director who loves podcasts. Looking for someone respectful, clean, and open to camping together.',
    occupation: 'Art Director',
    budget: 2400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=590',
      'https://picsum.photos/400/500?random=591',
      'https://picsum.photos/400/500?random=592',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'The Loop',
      moveInDate: '02/22/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 79,
  },
  {
    id: '60',
    name: 'Elijah Kelly',
    age: 26,
    zodiacSign: 'Libra',
    gender: 'other',
    bio: 'Passionate physical therapist looking for a like-minded roommate. Into skateboarding and volunteering.',
    occupation: 'Physical Therapist',
    budget: 1300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=600',
      'https://picsum.photos/400/500?random=601',
      'https://picsum.photos/400/500?random=602',
      'https://picsum.photos/400/500?random=603',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Wynwood',
      moveInDate: '06/05/2025',
      bedrooms: 2,
    },
    compatibility: 73,
  },
  {
    id: '61',
    name: 'Riley Castillo',
    age: 21,
    zodiacSign: 'Gemini',
    gender: 'other',
    bio: 'Ambitious real estate agent who values work-life balance. Enjoy pottery and thrifting on weekends.',
    occupation: 'Real Estate Agent',
    budget: 2200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=610',
      'https://picsum.photos/400/500?random=611',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Wynwood',
      moveInDate: '02/28/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 76,
  },
  {
    id: '62',
    name: 'Emma Watson',
    age: 23,
    zodiacSign: 'Aquarius',
    gender: 'female',
    bio: 'Fitness Trainer who loves thrifting. Looking for someone respectful, clean, and open to podcasts together.',
    occupation: 'Fitness Trainer',
    budget: 2200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=620',
      'https://picsum.photos/400/500?random=621',
      'https://picsum.photos/400/500?random=622',
      'https://picsum.photos/400/500?random=623',
      'https://picsum.photos/400/500?random=624',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Freelance',
      pets: true,
      smoking: true,
    },
    preferences: {
      location: 'Coconut Grove',
      moveInDate: '02/17/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 80,
  },
  {
    id: '63',
    name: 'Amelia Murphy',
    age: 30,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Film Editor by day, dancing enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Film Editor',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=630',
      'https://picsum.photos/400/500?random=631',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Coconut Grove',
      moveInDate: '04/27/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 66,
  },
  {
    id: '64',
    name: 'Layla Diaz',
    age: 32,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Musician who enjoys basketball and cycling. Looking for a chill and respectful roommate.',
    occupation: 'Musician',
    budget: 2000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=640',
      'https://picsum.photos/400/500?random=641',
      'https://picsum.photos/400/500?random=642',
      'https://picsum.photos/400/500?random=643',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 9,
      workSchedule: 'Student',
      pets: true,
      smoking: true,
    },
    preferences: {
      location: 'Wynwood',
      moveInDate: '02/27/2025',
      bedrooms: 2,
    },
    compatibility: 94,
  },
  {
    id: '65',
    name: 'Finley Nelson',
    age: 26,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Entrepreneur with a passion for cycling. Also love dancing. Looking for a compatible living situation.',
    occupation: 'Entrepreneur',
    budget: 1200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=650',
      'https://picsum.photos/400/500?random=651',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 5,
      workSchedule: 'Shifts',
      pets: true,
      smoking: true,
    },
    preferences: {
      location: 'Wynwood',
      moveInDate: '01/28/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 61,
  },
  {
    id: '66',
    name: 'Logan Kim',
    age: 23,
    zodiacSign: 'Scorpio',
    gender: 'female',
    bio: 'Civil Engineer who enjoys meditation and dancing. Looking for a chill and respectful roommate.',
    occupation: 'Civil Engineer',
    budget: 1400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=660',
      'https://picsum.photos/400/500?random=661',
      'https://picsum.photos/400/500?random=662',
      'https://picsum.photos/400/500?random=663',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 4,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Little Havana',
      moveInDate: '04/01/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 94,
  },
  {
    id: '67',
    name: 'Phoenix Sanders',
    age: 23,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Medical Resident who loves basketball. Looking for someone respectful, clean, and open to volunteering together.',
    occupation: 'Medical Resident',
    budget: 1900,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=670',
      'https://picsum.photos/400/500?random=671',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 8,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Coconut Grove',
      moveInDate: '04/13/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 90,
  },
  {
    id: '68',
    name: 'Daniel Myers',
    age: 30,
    zodiacSign: 'Pisces',
    gender: 'other',
    bio: 'Passionate graphic designer looking for a like-minded roommate. Into thrifting and tennis.',
    occupation: 'Graphic Designer',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=680',
      'https://picsum.photos/400/500?random=681',
      'https://picsum.photos/400/500?random=682',
      'https://picsum.photos/400/500?random=683',
      'https://picsum.photos/400/500?random=684',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Brickell',
      moveInDate: '06/06/2025',
      bedrooms: 3,
    },
    compatibility: 61,
  },
  {
    id: '69',
    name: 'Jayden Peterson',
    age: 24,
    zodiacSign: 'Sagittarius',
    gender: 'male',
    bio: 'Working as a social worker. Love dancing, writing, and trying new restaurants. Tidy and considerate.',
    occupation: 'Social Worker',
    budget: 1700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=690',
      'https://picsum.photos/400/500?random=691',
      'https://picsum.photos/400/500?random=692',
      'https://picsum.photos/400/500?random=693',
      'https://picsum.photos/400/500?random=694',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'Brickell',
      moveInDate: '03/28/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 78,
  },
  {
    id: '70',
    name: 'Finley Parker',
    age: 24,
    zodiacSign: 'Aries',
    gender: 'female',
    bio: 'Working as a event planner. Love gardening, photography, and trying new restaurants. Tidy and considerate.',
    occupation: 'Event Planner',
    budget: 900,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=700',
      'https://picsum.photos/400/500?random=701',
      'https://picsum.photos/400/500?random=702',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 8,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'SOMA',
      moveInDate: '05/02/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 65,
  },
  {
    id: '71',
    name: 'Rio Wood',
    age: 23,
    zodiacSign: 'Leo',
    gender: 'female',
    bio: 'Passionate fitness trainer looking for a like-minded roommate. Into meditation and gaming.',
    occupation: 'Fitness Trainer',
    budget: 2400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=710',
      'https://picsum.photos/400/500?random=711',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'SOMA',
      moveInDate: '05/08/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 71,
  },
  {
    id: '72',
    name: 'Rowan Long',
    age: 27,
    zodiacSign: 'Sagittarius',
    gender: 'male',
    bio: 'Passionate data analyst looking for a like-minded roommate. Into camping and wine tasting.',
    occupation: 'Data Analyst',
    budget: 900,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=720',
      'https://picsum.photos/400/500?random=721',
      'https://picsum.photos/400/500?random=722',
      'https://picsum.photos/400/500?random=723',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 4,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Mission District',
      moveInDate: '02/10/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 89,
  },
  {
    id: '73',
    name: 'Dakota Green',
    age: 33,
    zodiacSign: 'Taurus',
    gender: 'female',
    bio: 'Logistics Coordinator by day, podcasts enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Logistics Coordinator',
    budget: 2200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=730',
      'https://picsum.photos/400/500?random=731',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 3,
      workSchedule: 'Student',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Haight-Ashbury',
      moveInDate: '06/06/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 70,
  },
  {
    id: '74',
    name: 'Blair Collins',
    age: 27,
    zodiacSign: 'Aquarius',
    gender: 'male',
    bio: 'Pharmacist by day, dancing enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Pharmacist',
    budget: 1500,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=740',
      'https://picsum.photos/400/500?random=741',
      'https://picsum.photos/400/500?random=742',
      'https://picsum.photos/400/500?random=743',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 9,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Castro',
      moveInDate: '01/14/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 90,
  },
  {
    id: '75',
    name: 'Jackson Turner',
    age: 23,
    zodiacSign: 'Aquarius',
    gender: 'female',
    bio: 'Passionate pilot looking for a like-minded roommate. Into coffee tasting and cycling.',
    occupation: 'Pilot',
    budget: 2000,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=750',
      'https://picsum.photos/400/500?random=751',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 3,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Haight-Ashbury',
      moveInDate: '06/07/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 87,
  },
  {
    id: '76',
    name: 'Daniel Butler',
    age: 31,
    zodiacSign: 'Pisces',
    gender: 'male',
    bio: 'Friendly dentist seeking a tidy roommate. Big fan of yoga and swimming.',
    occupation: 'Dentist',
    budget: 2200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=760',
      'https://picsum.photos/400/500?random=761',
      'https://picsum.photos/400/500?random=762',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 8,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'SOMA',
      moveInDate: '06/24/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 81,
  },
  {
    id: '77',
    name: 'Abigail Brooks',
    age: 25,
    zodiacSign: 'Leo',
    gender: 'female',
    bio: 'Financial Analyst who enjoys yoga and tennis. Looking for a chill and respectful roommate.',
    occupation: 'Financial Analyst',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=770',
      'https://picsum.photos/400/500?random=771',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 8,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Mission District',
      moveInDate: '02/06/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 79,
  },
  {
    id: '78',
    name: 'Aurora Parker',
    age: 32,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Creative park ranger seeking a friendly roommate. Enjoy hiking, gaming, and weekend adventures.',
    occupation: 'Park Ranger',
    budget: 2400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=780',
      'https://picsum.photos/400/500?random=781',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Haight-Ashbury',
      moveInDate: '05/13/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 80,
  },
  {
    id: '79',
    name: 'Liam Price',
    age: 22,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Ambitious musician who values work-life balance. Enjoy hiking and volunteering on weekends.',
    occupation: 'Musician',
    budget: 700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=790',
      'https://picsum.photos/400/500?random=791',
      'https://picsum.photos/400/500?random=792',
      'https://picsum.photos/400/500?random=793',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 4,
      workSchedule: 'Student',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'North Beach SF',
      moveInDate: '02/12/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'instagram' },
    },
    compatibility: 77,
  },
  {
    id: '80',
    name: 'Kai Reed',
    age: 24,
    zodiacSign: 'Sagittarius',
    gender: 'female',
    bio: 'Software Engineer by day, wine tasting enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Software Engineer',
    budget: 700,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=800',
      'https://picsum.photos/400/500?random=801',
      'https://picsum.photos/400/500?random=802',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Flexible',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Hyde Park Austin',
      moveInDate: '02/25/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 73,
  },
  {
    id: '81',
    name: 'Owen Taylor',
    age: 31,
    zodiacSign: 'Cancer',
    gender: 'male',
    bio: 'Friendly mechanical engineer seeking a tidy roommate. Big fan of soccer and pottery.',
    occupation: 'Mechanical Engineer',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=810',
      'https://picsum.photos/400/500?random=811',
      'https://picsum.photos/400/500?random=812',
      'https://picsum.photos/400/500?random=813',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 8,
      workSchedule: 'Hybrid',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'East Austin',
      moveInDate: '03/20/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 65,
  },
  {
    id: '82',
    name: 'Jackson Brooks',
    age: 21,
    zodiacSign: 'Aquarius',
    gender: 'female',
    bio: 'Working as a photographer. Love traveling, film, and trying new restaurants. Tidy and considerate.',
    occupation: 'Photographer',
    budget: 1100,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=820',
      'https://picsum.photos/400/500?random=821',
      'https://picsum.photos/400/500?random=822',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Hyde Park Austin',
      moveInDate: '04/16/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 94,
  },
  {
    id: '83',
    name: 'Dylan Adams',
    age: 28,
    zodiacSign: 'Taurus',
    gender: 'female',
    bio: 'Working as a park ranger. Love coffee tasting, hiking, and trying new restaurants. Tidy and considerate.',
    occupation: 'Park Ranger',
    budget: 1700,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=830',
      'https://picsum.photos/400/500?random=831',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 6,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Downtown Austin',
      moveInDate: '03/02/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 92,
  },
  {
    id: '84',
    name: 'Mason Ruiz',
    age: 30,
    zodiacSign: 'Aries',
    gender: 'female',
    bio: 'Ambitious social worker who values work-life balance. Enjoy board games and running on weekends.',
    occupation: 'Social Worker',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=840',
      'https://picsum.photos/400/500?random=841',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Downtown Austin',
      moveInDate: '03/15/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 84,
  },
  {
    id: '85',
    name: 'Jayden Campbell',
    age: 25,
    zodiacSign: 'Taurus',
    gender: 'female',
    bio: 'Event Planner who loves writing. Looking for someone respectful, clean, and open to cooking together.',
    occupation: 'Event Planner',
    budget: 2000,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=850',
      'https://picsum.photos/400/500?random=851',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 9,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Mueller',
      moveInDate: '06/10/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 88,
  },
  {
    id: '86',
    name: 'Aurora Reed',
    age: 32,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Creative event planner seeking a friendly roommate. Enjoy traveling, gardening, and weekend adventures.',
    occupation: 'Event Planner',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=860',
      'https://picsum.photos/400/500?random=861',
      'https://picsum.photos/400/500?random=862',
      'https://picsum.photos/400/500?random=863',
      'https://picsum.photos/400/500?random=864',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 3,
      workSchedule: 'Hybrid',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Downtown Austin',
      moveInDate: '01/03/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 94,
  },
  {
    id: '87',
    name: 'Mason Martinez',
    age: 24,
    zodiacSign: 'Sagittarius',
    gender: 'female',
    bio: 'Insurance Agent by day, gardening enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Insurance Agent',
    budget: 1900,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=870',
      'https://picsum.photos/400/500?random=871',
      'https://picsum.photos/400/500?random=872',
      'https://picsum.photos/400/500?random=873',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Mueller',
      moveInDate: '04/18/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 70,
  },
  {
    id: '88',
    name: 'Harper Sullivan',
    age: 23,
    zodiacSign: 'Cancer',
    gender: 'male',
    bio: 'Architect by day, soccer enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Architect',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=880',
      'https://picsum.photos/400/500?random=881',
      'https://picsum.photos/400/500?random=882',
      'https://picsum.photos/400/500?random=883',
      'https://picsum.photos/400/500?random=884',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'East Austin',
      moveInDate: '04/16/2025',
      bedrooms: 1,
    },
    compatibility: 87,
  },
  {
    id: '89',
    name: 'Gabriel Fisher',
    age: 23,
    zodiacSign: 'Pisces',
    gender: 'male',
    bio: 'Real Estate Agent who loves tennis. Looking for someone respectful, clean, and open to baking together.',
    occupation: 'Real Estate Agent',
    budget: 800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=890',
      'https://picsum.photos/400/500?random=891',
      'https://picsum.photos/400/500?random=892',
      'https://picsum.photos/400/500?random=893',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 8,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Queen Anne',
      moveInDate: '06/01/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 69,
  },
  {
    id: '90',
    name: 'Sophia Ruiz',
    age: 22,
    zodiacSign: 'Libra',
    gender: 'male',
    bio: 'Working as a accountant. Love thrifting, photography, and trying new restaurants. Tidy and considerate.',
    occupation: 'Accountant',
    budget: 1200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=900',
      'https://picsum.photos/400/500?random=901',
      'https://picsum.photos/400/500?random=902',
      'https://picsum.photos/400/500?random=903',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Freelance',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Ballard',
      moveInDate: '05/13/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 81,
  },
  {
    id: '91',
    name: 'Emerson Reyes',
    age: 25,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Ambitious biotech researcher who values work-life balance. Enjoy podcasts and pottery on weekends.',
    occupation: 'Biotech Researcher',
    budget: 800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=910',
      'https://picsum.photos/400/500?random=911',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 9,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Ballard',
      moveInDate: '02/26/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 92,
  },
  {
    id: '92',
    name: 'Riley Mendoza',
    age: 30,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Working as a nurse. Love tennis, writing, and trying new restaurants. Tidy and considerate.',
    occupation: 'Nurse',
    budget: 2400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=920',
      'https://picsum.photos/400/500?random=921',
      'https://picsum.photos/400/500?random=922',
      'https://picsum.photos/400/500?random=923',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 5,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Ballard',
      moveInDate: '03/08/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 60,
  },
  {
    id: '93',
    name: 'Avery Rogers',
    age: 29,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Working as a physical therapist. Love pottery, skateboarding, and trying new restaurants. Tidy and considerate.',
    occupation: 'Physical Therapist',
    budget: 2000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=930',
      'https://picsum.photos/400/500?random=931',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 8,
      workSchedule: 'Flexible',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Belltown',
      moveInDate: '04/07/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 80,
  },
  {
    id: '94',
    name: 'Sebastian Brown',
    age: 26,
    zodiacSign: 'Sagittarius',
    gender: 'female',
    bio: 'Social Worker by day, surfing enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Social Worker',
    budget: 2200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=940',
      'https://picsum.photos/400/500?random=941',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Queen Anne',
      moveInDate: '05/05/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 62,
  },
  {
    id: '95',
    name: 'Layla Carter',
    age: 24,
    zodiacSign: 'Gemini',
    gender: 'male',
    bio: 'Laid-back urban planner into dancing and traveling. Prefer a quiet home with occasional social hangouts.',
    occupation: 'Urban Planner',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=950',
      'https://picsum.photos/400/500?random=951',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'South Lake Union',
      moveInDate: '01/01/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'instagram' },
    },
    compatibility: 74,
  },
  {
    id: '96',
    name: 'Emma Price',
    age: 34,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Financial Analyst who enjoys hiking and fitness. Looking for a chill and respectful roommate.',
    occupation: 'Financial Analyst',
    budget: 700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=960',
      'https://picsum.photos/400/500?random=961',
      'https://picsum.photos/400/500?random=962',
      'https://picsum.photos/400/500?random=963',
      'https://picsum.photos/400/500?random=964',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Fremont',
      moveInDate: '06/01/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 89,
  },
  {
    id: '97',
    name: 'Violet Morris',
    age: 22,
    zodiacSign: 'Leo',
    gender: 'female',
    bio: 'Ambitious content creator who values work-life balance. Enjoy dancing and rock climbing on weekends.',
    occupation: 'Content Creator',
    budget: 2300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=970',
      'https://picsum.photos/400/500?random=971',
      'https://picsum.photos/400/500?random=972',
      'https://picsum.photos/400/500?random=973',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 8,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Belltown',
      moveInDate: '01/23/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 90,
  },
  {
    id: '98',
    name: 'Blair Bailey',
    age: 30,
    zodiacSign: 'Taurus',
    gender: 'female',
    bio: 'Interior Designer by day, soccer enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Interior Designer',
    budget: 2400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=980',
      'https://picsum.photos/400/500?random=981',
      'https://picsum.photos/400/500?random=982',
      'https://picsum.photos/400/500?random=983',
      'https://picsum.photos/400/500?random=984',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 8,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Washington Park',
      moveInDate: '04/14/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 63,
  },
  {
    id: '99',
    name: 'Reese Flores',
    age: 27,
    zodiacSign: 'Aries',
    gender: 'female',
    bio: 'Ambitious graduate student who values work-life balance. Enjoy live music and martial arts on weekends.',
    occupation: 'Graduate Student',
    budget: 800,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=990',
      'https://picsum.photos/400/500?random=991',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 4,
      workSchedule: 'Remote',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'LoDo',
      moveInDate: '01/09/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 86,
  },
  {
    id: '100',
    name: 'Blair Torres',
    age: 34,
    zodiacSign: 'Taurus',
    gender: 'female',
    bio: 'Ambitious social worker who values work-life balance. Enjoy baking and rock climbing on weekends.',
    occupation: 'Social Worker',
    budget: 2000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1000',
      'https://picsum.photos/400/500?random=1001',
      'https://picsum.photos/400/500?random=1002',
      'https://picsum.photos/400/500?random=1003',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Washington Park',
      moveInDate: '05/04/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 85,
  },
  {
    id: '101',
    name: 'Emma Henderson',
    age: 25,
    zodiacSign: 'Libra',
    gender: 'other',
    bio: 'Friendly social worker seeking a tidy roommate. Big fan of camping and basketball.',
    occupation: 'Social Worker',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1010',
      'https://picsum.photos/400/500?random=1011',
      'https://picsum.photos/400/500?random=1012',
      'https://picsum.photos/400/500?random=1013',
      'https://picsum.photos/400/500?random=1014',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 5,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'RiNo',
      moveInDate: '04/21/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 86,
  },
  {
    id: '102',
    name: 'Ava Barnes',
    age: 28,
    zodiacSign: 'Leo',
    gender: 'female',
    bio: 'Ambitious art director who values work-life balance. Enjoy fitness and dancing on weekends.',
    occupation: 'Art Director',
    budget: 1900,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1020',
      'https://picsum.photos/400/500?random=1021',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Five Points',
      moveInDate: '05/27/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 61,
  },
  {
    id: '103',
    name: 'Logan Reyes',
    age: 32,
    zodiacSign: 'Libra',
    gender: 'male',
    bio: 'Creative librarian seeking a friendly roommate. Enjoy pottery, rock climbing, and weekend adventures.',
    occupation: 'Librarian',
    budget: 900,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1030',
      'https://picsum.photos/400/500?random=1031',
      'https://picsum.photos/400/500?random=1032',
      'https://picsum.photos/400/500?random=1033',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'LoDo',
      moveInDate: '04/14/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 87,
  },
  {
    id: '104',
    name: 'Daniel Sanders',
    age: 27,
    zodiacSign: 'Aries',
    gender: 'female',
    bio: 'Ambitious data analyst who values work-life balance. Enjoy meditation and running on weekends.',
    occupation: 'Data Analyst',
    budget: 2100,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1040',
      'https://picsum.photos/400/500?random=1041',
      'https://picsum.photos/400/500?random=1042',
      'https://picsum.photos/400/500?random=1043',
      'https://picsum.photos/400/500?random=1044',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 4,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Five Points',
      moveInDate: '06/09/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 77,
  },
  {
    id: '105',
    name: 'Violet Griffin',
    age: 32,
    zodiacSign: 'Pisces',
    gender: 'male',
    bio: 'Ambitious biotech researcher who values work-life balance. Enjoy painting and kayaking on weekends.',
    occupation: 'Biotech Researcher',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1050',
      'https://picsum.photos/400/500?random=1051',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Cherry Creek',
      moveInDate: '04/11/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 80,
  },
  {
    id: '106',
    name: 'Oliver Nelson',
    age: 21,
    zodiacSign: 'Capricorn',
    gender: 'female',
    bio: 'UX Designer who loves hiking. Looking for someone respectful, clean, and open to cooking together.',
    occupation: 'UX Designer',
    budget: 2300,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1060',
      'https://picsum.photos/400/500?random=1061',
      'https://picsum.photos/400/500?random=1062',
      'https://picsum.photos/400/500?random=1063',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Fenway',
      moveInDate: '05/04/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 76,
  },
  {
    id: '107',
    name: 'Casey Richardson',
    age: 22,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Laid-back biotech researcher into camping and cooking. Prefer a quiet home with occasional social hangouts.',
    occupation: 'Biotech Researcher',
    budget: 1600,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1070',
      'https://picsum.photos/400/500?random=1071',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Cambridge',
      moveInDate: '06/09/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 73,
  },
  {
    id: '108',
    name: 'Jackson Kelly',
    age: 33,
    zodiacSign: 'Taurus',
    gender: 'female',
    bio: 'Fitness Trainer by day, kayaking enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Fitness Trainer',
    budget: 1200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1080',
      'https://picsum.photos/400/500?random=1081',
      'https://picsum.photos/400/500?random=1082',
      'https://picsum.photos/400/500?random=1083',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Fenway',
      moveInDate: '03/08/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 64,
  },
  {
    id: '109',
    name: 'Taylor Hill',
    age: 27,
    zodiacSign: 'Sagittarius',
    gender: 'other',
    bio: 'Working as a graphic designer. Love swimming, live music, and trying new restaurants. Tidy and considerate.',
    occupation: 'Graphic Designer',
    budget: 1100,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1090',
      'https://picsum.photos/400/500?random=1091',
      'https://picsum.photos/400/500?random=1092',
      'https://picsum.photos/400/500?random=1093',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 3,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'South End',
      moveInDate: '02/08/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 64,
  },
  {
    id: '110',
    name: 'Jayden Patel',
    age: 27,
    zodiacSign: 'Aquarius',
    gender: 'female',
    bio: 'Urban Planner who enjoys pottery and running. Looking for a chill and respectful roommate.',
    occupation: 'Urban Planner',
    budget: 2300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1100',
      'https://picsum.photos/400/500?random=1101',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 3,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Back Bay',
      moveInDate: '05/08/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 90,
  },
  {
    id: '111',
    name: 'Penelope Price',
    age: 34,
    zodiacSign: 'Gemini',
    gender: 'other',
    bio: 'Research Scientist by day, martial arts enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Research Scientist',
    budget: 1400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1110',
      'https://picsum.photos/400/500?random=1111',
      'https://picsum.photos/400/500?random=1112',
      'https://picsum.photos/400/500?random=1113',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 4,
      workSchedule: 'Freelance',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'South Boston',
      moveInDate: '04/24/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 68,
  },
  {
    id: '112',
    name: 'Rio Campbell',
    age: 22,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Friendly fitness trainer seeking a tidy roommate. Big fan of music and kayaking.',
    occupation: 'Fitness Trainer',
    budget: 2400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1120',
      'https://picsum.photos/400/500?random=1121',
      'https://picsum.photos/400/500?random=1122',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Cambridge',
      moveInDate: '02/12/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 64,
  },
  {
    id: '113',
    name: 'Mason Price',
    age: 21,
    zodiacSign: 'Leo',
    gender: 'male',
    bio: 'Laid-back graphic designer into board games and cooking. Prefer a quiet home with occasional social hangouts.',
    occupation: 'Graphic Designer',
    budget: 2000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1130',
      'https://picsum.photos/400/500?random=1131',
      'https://picsum.photos/400/500?random=1132',
      'https://picsum.photos/400/500?random=1133',
      'https://picsum.photos/400/500?random=1134',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'South End',
      moveInDate: '03/17/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 80,
  },
  {
    id: '114',
    name: 'Wyatt Rogers',
    age: 22,
    zodiacSign: 'Pisces',
    gender: 'other',
    bio: 'Laid-back barista into board games and traveling. Prefer a quiet home with occasional social hangouts.',
    occupation: 'Barista',
    budget: 2100,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1140',
      'https://picsum.photos/400/500?random=1141',
      'https://picsum.photos/400/500?random=1142',
      'https://picsum.photos/400/500?random=1143',
      'https://picsum.photos/400/500?random=1144',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Midtown Houston',
      moveInDate: '06/25/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 85,
  },
  {
    id: '115',
    name: 'Ethan Foster',
    age: 25,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Friendly physical therapist seeking a tidy roommate. Big fan of baking and board games.',
    occupation: 'Physical Therapist',
    budget: 1500,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1150',
      'https://picsum.photos/400/500?random=1151',
      'https://picsum.photos/400/500?random=1152',
      'https://picsum.photos/400/500?random=1153',
      'https://picsum.photos/400/500?random=1154',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Rice Village',
      moveInDate: '02/07/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 72,
  },
  {
    id: '116',
    name: 'Mason Williams',
    age: 31,
    zodiacSign: 'Gemini',
    gender: 'male',
    bio: 'Ambitious biotech researcher who values work-life balance. Enjoy photography and reading on weekends.',
    occupation: 'Biotech Researcher',
    budget: 800,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1160',
      'https://picsum.photos/400/500?random=1161',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 3,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Rice Village',
      moveInDate: '01/14/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 88,
  },
  {
    id: '117',
    name: 'Blair Cox',
    age: 25,
    zodiacSign: 'Scorpio',
    gender: 'other',
    bio: 'Accountant who loves meditation. Looking for someone respectful, clean, and open to gaming together.',
    occupation: 'Accountant',
    budget: 2000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1170',
      'https://picsum.photos/400/500?random=1171',
      'https://picsum.photos/400/500?random=1172',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'The Heights Houston',
      moveInDate: '04/13/2025',
      bedrooms: 3,
    },
    compatibility: 65,
  },
  {
    id: '118',
    name: 'Sophia Allen',
    age: 27,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Project Manager with a passion for traveling. Also love wine tasting. Looking for a compatible living situation.',
    occupation: 'Project Manager',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1180',
      'https://picsum.photos/400/500?random=1181',
      'https://picsum.photos/400/500?random=1182',
      'https://picsum.photos/400/500?random=1183',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 9,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Museum District',
      moveInDate: '05/11/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 73,
  },
  {
    id: '119',
    name: 'Wyatt Bailey',
    age: 22,
    zodiacSign: 'Sagittarius',
    gender: 'female',
    bio: 'Financial Analyst who enjoys coffee tasting and writing. Looking for a chill and respectful roommate.',
    occupation: 'Financial Analyst',
    budget: 2400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1190',
      'https://picsum.photos/400/500?random=1191',
      'https://picsum.photos/400/500?random=1192',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Hybrid',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Montrose',
      moveInDate: '02/07/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'instagram' },
    },
    compatibility: 87,
  },
  {
    id: '120',
    name: 'Charlotte Scott',
    age: 28,
    zodiacSign: 'Cancer',
    gender: 'male',
    bio: 'Passionate logistics coordinator looking for a like-minded roommate. Into skateboarding and volunteering.',
    occupation: 'Logistics Coordinator',
    budget: 2300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1200',
      'https://picsum.photos/400/500?random=1201',
      'https://picsum.photos/400/500?random=1202',
      'https://picsum.photos/400/500?random=1203',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 9,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'EaDo',
      moveInDate: '04/17/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 86,
  },
  {
    id: '121',
    name: 'Violet Stewart',
    age: 30,
    zodiacSign: 'Leo',
    gender: 'male',
    bio: 'Interior Designer by day, running enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Interior Designer',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1210',
      'https://picsum.photos/400/500?random=1211',
      'https://picsum.photos/400/500?random=1212',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 9,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Midtown Atlanta',
      moveInDate: '02/12/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 80,
  },
  {
    id: '122',
    name: 'Sage Cox',
    age: 29,
    zodiacSign: 'Leo',
    gender: 'other',
    bio: 'Ambitious musician who values work-life balance. Enjoy camping and basketball on weekends.',
    occupation: 'Musician',
    budget: 900,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1220',
      'https://picsum.photos/400/500?random=1221',
      'https://picsum.photos/400/500?random=1222',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Midtown Atlanta',
      moveInDate: '03/07/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'facebook' },
    },
    compatibility: 93,
  },
  {
    id: '123',
    name: 'Violet Edwards',
    age: 29,
    zodiacSign: 'Scorpio',
    gender: 'other',
    bio: 'Entrepreneur with a passion for wine tasting. Also love camping. Looking for a compatible living situation.',
    occupation: 'Entrepreneur',
    budget: 2400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1230',
      'https://picsum.photos/400/500?random=1231',
      'https://picsum.photos/400/500?random=1232',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 3,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Midtown Atlanta',
      moveInDate: '04/15/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-03'), platform: 'linkedin' },
    },
    compatibility: 61,
  },
  {
    id: '124',
    name: 'Noah Cooper',
    age: 26,
    zodiacSign: 'Aries',
    gender: 'female',
    bio: 'Laid-back dentist into writing and basketball. Prefer a quiet home with occasional social hangouts.',
    occupation: 'Dentist',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1240',
      'https://picsum.photos/400/500?random=1241',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 3,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Virginia-Highland',
      moveInDate: '04/26/2025',
      bedrooms: 2,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 64,
  },
  {
    id: '125',
    name: 'Casey Collins',
    age: 26,
    zodiacSign: 'Gemini',
    gender: 'male',
    bio: 'Chef with a passion for live music. Also love music. Looking for a compatible living situation.',
    occupation: 'Chef',
    budget: 1200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1250',
      'https://picsum.photos/400/500?random=1251',
      'https://picsum.photos/400/500?random=1252',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Student',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Inman Park',
      moveInDate: '01/03/2025',
      bedrooms: 1,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 77,
  },
  {
    id: '126',
    name: 'Blair Cooper',
    age: 22,
    zodiacSign: 'Capricorn',
    gender: 'female',
    bio: 'Photographer by day, meditation enthusiast by night. Seeking a roommate who values clean spaces and good vibes.',
    occupation: 'Photographer',
    budget: 1600,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1260',
      'https://picsum.photos/400/500?random=1261',
      'https://picsum.photos/400/500?random=1262',
      'https://picsum.photos/400/500?random=1263',
      'https://picsum.photos/400/500?random=1264',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 5,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Inman Park',
      moveInDate: '03/06/2025',
      bedrooms: 3,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 69,
  },
];
