import { Conversation, Property, Group, Application } from '../types/models';
import { getCityFromNeighborhood, getStateFromNeighborhood, getCoordinatesFromNeighborhood } from './locationData';

export const extraConversations: Conversation[] = [
  {
    id: '3',
    participant: {
      id: '3',
      name: 'Emily Rodriguez',
      photo: 'https://picsum.photos/100/100?random=3',
      online: true,
    },
    lastMessage: 'I love that neighborhood! Do you have a move-in date in mind?',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    unread: 1,
    messages: [],
  },
  {
    id: '4',
    participant: {
      id: '4',
      name: 'Bob Anderson',
      photo: 'https://picsum.photos/100/100?random=4',
      online: false,
    },
    lastMessage: 'I can meet tomorrow afternoon for a walkthrough if that works.',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    unread: 0,
    messages: [],
  },
  {
    id: '5',
    participant: {
      id: '5',
      name: 'Jessica Park',
      photo: 'https://picsum.photos/100/100?random=5',
      online: true,
    },
    lastMessage: 'The room is still available! Want to set up a video call?',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    unread: 3,
    messages: [],
  },
  {
    id: '6',
    participant: {
      id: '6',
      name: 'David Martinez',
      photo: 'https://picsum.photos/100/100?random=6',
      online: false,
    },
    lastMessage: 'Great, I will send over the lease details tonight.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
    unread: 0,
    messages: [],
  },
  {
    id: '7',
    participant: {
      id: '7',
      name: 'Amanda White',
      photo: 'https://picsum.photos/100/100?random=7',
      online: true,
    },
    lastMessage: 'My dog is super friendly, promise! He mostly just naps.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
    unread: 2,
    messages: [],
  },
  {
    id: '8',
    participant: {
      id: '8',
      name: 'Ryan Thompson',
      photo: 'https://picsum.photos/100/100?random=8',
      online: false,
    },
    lastMessage: 'The internet speed is 500mbps, perfect for remote work.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
    unread: 0,
    messages: [],
  },
  {
    id: '9',
    participant: {
      id: '9',
      name: 'Amanda Lee',
      photo: 'https://picsum.photos/100/100?random=9',
      online: true,
    },
    lastMessage: 'I just submitted my application for that listing you shared!',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
    unread: 1,
    messages: [],
  },
  {
    id: '10',
    participant: {
      id: '10',
      name: 'Ryan Garcia',
      photo: 'https://picsum.photos/100/100?random=10',
      online: false,
    },
    lastMessage: 'Utilities are split evenly between all roommates.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 18),
    unread: 0,
    messages: [],
  },
  {
    id: '11',
    participant: {
      id: '11',
      name: 'Sophia Brown',
      photo: 'https://picsum.photos/100/100?random=11',
      online: true,
    },
    lastMessage: 'Can you tell me more about the parking situation?',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    unread: 4,
    messages: [],
  },
  {
    id: '12',
    participant: {
      id: '12',
      name: 'Matthew Davis',
      photo: 'https://picsum.photos/100/100?random=12',
      online: false,
    },
    lastMessage: 'Sounds good, I will bring the deposit check to the signing.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 30),
    unread: 0,
    messages: [],
  },
  {
    id: '13',
    participant: {
      id: '13',
      name: 'Olivia Miller',
      photo: 'https://picsum.photos/100/100?random=13',
      online: true,
    },
    lastMessage: 'I work night shifts so I need a quiet place during the day.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 36),
    unread: 2,
    messages: [],
  },
  {
    id: '14',
    participant: {
      id: '14',
      name: 'Daniel Moore',
      photo: 'https://picsum.photos/100/100?random=14',
      online: false,
    },
    lastMessage: 'The gym in the building is open 24/7 which is amazing.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48),
    unread: 0,
    messages: [],
  },
  {
    id: '15',
    participant: {
      id: '15',
      name: 'Emma Taylor',
      photo: 'https://picsum.photos/100/100?random=15',
      online: false,
    },
    lastMessage: 'I saw your group posting - would love to join!',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 60),
    unread: 1,
    messages: [],
  },
  {
    id: '16',
    participant: {
      id: '16',
      name: 'Alex Kumar',
      photo: 'https://picsum.photos/100/100?random=16',
      online: true,
    },
    lastMessage: 'We should coordinate on furniture - I have a couch already.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72),
    unread: 5,
    messages: [],
  },
  {
    id: '17',
    participant: {
      id: '17',
      name: 'Mia Johnson',
      photo: 'https://picsum.photos/100/100?random=17',
      online: false,
    },
    lastMessage: 'Perfect, the lease starts on the 1st. See you at the signing!',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 96),
    unread: 0,
    messages: [],
  },
];

export const extraProperties: Property[] = [
  {
    id: '21',
    title: 'Silver Lake Bungalow',
    price: 2600,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 950,
    address: '1845 Silver Lake Blvd',
    city: getCityFromNeighborhood('Silver Lake') || 'Los Angeles',
    state: getStateFromNeighborhood('Silver Lake') || 'CA',
    neighborhood: 'Silver Lake',
    coordinates: getCoordinatesFromNeighborhood('Silver Lake') || undefined,
    photos: ['https://picsum.photos/800/600?random=3001'],
    amenities: ['Parking', 'Laundry', 'Pet Friendly', 'Balcony'],
    description: 'Charming bungalow in the heart of Silver Lake with mountain views and a sunny patio.',
    available: true,
    hostId: '21',
    hostName: 'Carlos Reyes',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 85,
  },
  {
    id: '22',
    title: 'Venice Beach Studio',
    price: 1800,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    address: '220 Pacific Ave',
    city: getCityFromNeighborhood('Venice') || 'Los Angeles',
    state: getStateFromNeighborhood('Venice') || 'CA',
    neighborhood: 'Venice',
    coordinates: getCoordinatesFromNeighborhood('Venice') || undefined,
    photos: ['https://picsum.photos/800/600?random=3002'],
    amenities: ['Balcony', 'Hardwood Floors', 'Central AC'],
    description: 'Steps from the beach in vibrant Venice. Open floor plan with natural light.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 92,
  },
  {
    id: '23',
    title: 'Wicker Park Loft',
    price: 1900,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 1100,
    address: '1456 N Milwaukee Ave',
    city: getCityFromNeighborhood('Wicker Park') || 'Chicago',
    state: getStateFromNeighborhood('Wicker Park') || 'IL',
    neighborhood: 'Wicker Park',
    coordinates: getCoordinatesFromNeighborhood('Wicker Park') || undefined,
    photos: ['https://picsum.photos/800/600?random=3003'],
    amenities: ['Hardwood Floors', 'In-Unit Laundry', 'Central AC', 'Storage'],
    description: 'Industrial-chic loft with exposed brick in trendy Wicker Park. Walk to restaurants and nightlife.',
    available: true,
    hostId: '23',
    hostName: 'Terrence Brooks',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 95,
  },
  {
    id: '24',
    title: 'Lincoln Park Brownstone Room',
    price: 1100,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    address: '832 W Fullerton Ave',
    city: getCityFromNeighborhood('Lincoln Park') || 'Chicago',
    state: getStateFromNeighborhood('Lincoln Park') || 'IL',
    neighborhood: 'Lincoln Park',
    coordinates: getCoordinatesFromNeighborhood('Lincoln Park') || undefined,
    photos: ['https://picsum.photos/800/600?random=3004'],
    amenities: ['Backyard', 'Laundry', 'Pet Friendly', 'Dishwasher'],
    description: 'Spacious room in classic brownstone. Near Lincoln Park Zoo and lakefront trail.',
    available: true,
    hostId: '26',
    hostName: 'Aisha Mohammed',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'female', onApp: true, userId: '26' },
      { gender: 'male', onApp: false },
    ],
    walkScore: 93,
  },
  {
    id: '25',
    title: 'Brickell Luxury Condo',
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1300,
    address: '1450 Brickell Ave',
    city: getCityFromNeighborhood('Brickell') || 'Miami',
    state: getStateFromNeighborhood('Brickell') || 'FL',
    neighborhood: 'Brickell',
    coordinates: getCoordinatesFromNeighborhood('Brickell') || undefined,
    photos: ['https://picsum.photos/800/600?random=3005'],
    amenities: ['Gym', 'Pool', 'Concierge', 'Parking', 'Rooftop Deck'],
    description: 'Stunning luxury condo in Brickell with bay views and world-class amenities.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 96,
  },
  {
    id: '26',
    title: 'Coconut Grove Cottage',
    price: 2100,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    address: '3340 Main Hwy',
    city: getCityFromNeighborhood('Coconut Grove') || 'Miami',
    state: getStateFromNeighborhood('Coconut Grove') || 'FL',
    neighborhood: 'Coconut Grove',
    coordinates: getCoordinatesFromNeighborhood('Coconut Grove') || undefined,
    photos: ['https://picsum.photos/800/600?random=3006'],
    amenities: ['Backyard', 'Pet Friendly', 'Parking', 'Laundry'],
    description: 'Tropical cottage surrounded by lush greenery. Walking distance to bayfront parks.',
    available: true,
    hostId: '24',
    hostName: 'Valentina Cruz',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 82,
  },
  {
    id: '27',
    title: 'Mission District Flat',
    price: 2800,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    address: '2755 Mission St',
    city: getCityFromNeighborhood('Mission District') || 'San Francisco',
    state: getStateFromNeighborhood('Mission District') || 'CA',
    neighborhood: 'Mission District',
    coordinates: getCoordinatesFromNeighborhood('Mission District') || undefined,
    photos: ['https://picsum.photos/800/600?random=3007'],
    amenities: ['Hardwood Floors', 'In-Unit Laundry', 'Central AC'],
    description: 'Sunny flat in the vibrant Mission with amazing murals and food scene at your doorstep.',
    available: true,
    hostId: '22',
    hostName: 'Priya Sharma',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 97,
  },
  {
    id: '28',
    title: 'Castro Victorian Room',
    price: 1500,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    address: '451 Castro St',
    city: getCityFromNeighborhood('Castro') || 'San Francisco',
    state: getStateFromNeighborhood('Castro') || 'CA',
    neighborhood: 'Castro',
    coordinates: getCoordinatesFromNeighborhood('Castro') || undefined,
    photos: ['https://picsum.photos/800/600?random=3008'],
    amenities: ['Hardwood Floors', 'Backyard', 'Laundry', 'Storage'],
    description: 'Charming room in a beautifully restored Victorian. Welcoming household with shared living spaces.',
    available: true,
    hostId: '22',
    hostName: 'Priya Sharma',
    featured: false,
    propertyType: 'sublet',
    roomType: 'room',
    existingRoommates: [
      { gender: 'female', onApp: true, userId: '22' },
      { gender: 'other', onApp: false },
    ],
    walkScore: 95,
  },
  {
    id: '29',
    title: 'East Austin Modern Home',
    price: 2200,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    address: '1210 E 6th St',
    city: getCityFromNeighborhood('East Austin') || 'Austin',
    state: getStateFromNeighborhood('East Austin') || 'TX',
    neighborhood: 'East Austin',
    coordinates: getCoordinatesFromNeighborhood('East Austin') || undefined,
    photos: ['https://picsum.photos/800/600?random=3009'],
    amenities: ['Parking', 'Backyard', 'Central AC', 'Pet Friendly'],
    description: 'Newly built modern home in East Austin. Close to Rainey Street and downtown.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 88,
  },
  {
    id: '30',
    title: 'South Congress Shared House',
    price: 950,
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1800,
    address: '1600 S Congress Ave',
    city: getCityFromNeighborhood('South Congress') || 'Austin',
    state: getStateFromNeighborhood('South Congress') || 'TX',
    neighborhood: 'South Congress',
    coordinates: getCoordinatesFromNeighborhood('South Congress') || undefined,
    photos: ['https://picsum.photos/800/600?random=3010'],
    amenities: ['Backyard', 'Parking', 'Laundry', 'Pet Friendly'],
    description: 'Room in a fun shared house on SoCo. Walk to live music venues and food trucks.',
    available: true,
    hostId: '15',
    hostName: 'Emma Taylor',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'female', onApp: false },
      { gender: 'male', onApp: false },
      { gender: 'female', onApp: true, userId: '15' },
    ],
    walkScore: 90,
  },
  {
    id: '31',
    title: 'Capitol Hill Seattle Apartment',
    price: 2400,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    address: '1122 E Pike St',
    city: getCityFromNeighborhood('Capitol Hill Seattle') || 'Seattle',
    state: getStateFromNeighborhood('Capitol Hill Seattle') || 'WA',
    neighborhood: 'Capitol Hill Seattle',
    coordinates: getCoordinatesFromNeighborhood('Capitol Hill Seattle') || undefined,
    photos: ['https://picsum.photos/800/600?random=3011'],
    amenities: ['In-Unit Laundry', 'Hardwood Floors', 'Central AC', 'Storage'],
    description: 'Hip apartment in the heart of Capitol Hill. Steps from nightlife, coffee shops, and parks.',
    available: true,
    hostId: '25',
    hostName: 'Jason Nakamura',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 96,
  },
  {
    id: '32',
    title: 'Ballard Craftsman Room',
    price: 1050,
    bedrooms: 3,
    bathrooms: 1,
    sqft: 1200,
    address: '5520 22nd Ave NW',
    city: getCityFromNeighborhood('Ballard') || 'Seattle',
    state: getStateFromNeighborhood('Ballard') || 'WA',
    neighborhood: 'Ballard',
    coordinates: getCoordinatesFromNeighborhood('Ballard') || undefined,
    photos: ['https://picsum.photos/800/600?random=3012'],
    amenities: ['Backyard', 'Laundry', 'Pet Friendly'],
    description: 'Cozy room in a classic Craftsman home. Near Ballard Locks and the Sunday farmers market.',
    available: true,
    hostId: '25',
    hostName: 'Jason Nakamura',
    featured: false,
    propertyType: 'sublet',
    roomType: 'room',
    existingRoommates: [
      { gender: 'male', onApp: true, userId: '25' },
      { gender: 'female', onApp: false },
    ],
    walkScore: 87,
  },
  {
    id: '33',
    title: 'RiNo Loft',
    price: 2000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    address: '3456 Walnut St',
    city: getCityFromNeighborhood('RiNo') || 'Denver',
    state: getStateFromNeighborhood('RiNo') || 'CO',
    neighborhood: 'RiNo',
    coordinates: getCoordinatesFromNeighborhood('RiNo') || undefined,
    photos: ['https://picsum.photos/800/600?random=3013'],
    amenities: ['Gym', 'Rooftop Deck', 'In-Unit Laundry', 'Parking'],
    description: 'Trendy loft in the River North Art District. Surrounded by breweries, galleries, and restaurants.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 89,
  },
  {
    id: '34',
    title: 'Capitol Hill Denver Shared',
    price: 900,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1300,
    address: '1245 E Colfax Ave',
    city: getCityFromNeighborhood('Capitol Hill Denver') || 'Denver',
    state: getStateFromNeighborhood('Capitol Hill Denver') || 'CO',
    neighborhood: 'Capitol Hill Denver',
    coordinates: getCoordinatesFromNeighborhood('Capitol Hill Denver') || undefined,
    photos: ['https://picsum.photos/800/600?random=3014'],
    amenities: ['Laundry', 'Hardwood Floors', 'Pet Friendly'],
    description: 'Affordable room in a friendly Capitol Hill house. Walking distance to Cheesman Park.',
    available: true,
    hostId: '12',
    hostName: 'Matthew Davis',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'male', onApp: true, userId: '12' },
      { gender: 'male', onApp: false },
    ],
    walkScore: 91,
  },
  {
    id: '35',
    title: 'Back Bay Brownstone',
    price: 3500,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    address: '330 Commonwealth Ave',
    city: getCityFromNeighborhood('Back Bay') || 'Boston',
    state: getStateFromNeighborhood('Back Bay') || 'MA',
    neighborhood: 'Back Bay',
    coordinates: getCoordinatesFromNeighborhood('Back Bay') || undefined,
    photos: ['https://picsum.photos/800/600?random=3015'],
    amenities: ['Doorman', 'Elevator', 'Central AC', 'In-Unit Laundry'],
    description: 'Elegant brownstone apartment on tree-lined Commonwealth Ave. Near shops and the T.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 97,
  },
  {
    id: '36',
    title: 'Cambridge Student Housing',
    price: 1200,
    bedrooms: 3,
    bathrooms: 1,
    sqft: 1000,
    address: '88 Harvard St',
    city: getCityFromNeighborhood('Cambridge') || 'Boston',
    state: getStateFromNeighborhood('Cambridge') || 'MA',
    neighborhood: 'Cambridge',
    coordinates: getCoordinatesFromNeighborhood('Cambridge') || undefined,
    photos: ['https://picsum.photos/800/600?random=3016'],
    amenities: ['Laundry', 'Storage', 'Hardwood Floors'],
    description: 'Affordable room near Harvard and MIT campuses. Great for students and young professionals.',
    available: true,
    hostId: '13',
    hostName: 'Olivia Miller',
    featured: false,
    propertyType: 'sublet',
    roomType: 'room',
    existingRoommates: [
      { gender: 'female', onApp: true, userId: '13' },
      { gender: 'female', onApp: false },
    ],
    walkScore: 94,
  },
  {
    id: '37',
    title: 'Montrose Bungalow',
    price: 1700,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    address: '1920 Westheimer Rd',
    city: getCityFromNeighborhood('Montrose') || 'Houston',
    state: getStateFromNeighborhood('Montrose') || 'TX',
    neighborhood: 'Montrose',
    coordinates: getCoordinatesFromNeighborhood('Montrose') || undefined,
    photos: ['https://picsum.photos/800/600?random=3017'],
    amenities: ['Parking', 'Backyard', 'Pet Friendly', 'Central AC'],
    description: 'Eclectic bungalow in artsy Montrose. Near galleries, vintage shops, and parks.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 83,
  },
  {
    id: '38',
    title: 'Heights Townhome Room',
    price: 800,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    address: '455 Heights Blvd',
    city: getCityFromNeighborhood('The Heights Houston') || 'Houston',
    state: getStateFromNeighborhood('The Heights Houston') || 'TX',
    neighborhood: 'The Heights Houston',
    coordinates: getCoordinatesFromNeighborhood('The Heights Houston') || undefined,
    photos: ['https://picsum.photos/800/600?random=3018'],
    amenities: ['Parking', 'Backyard', 'Laundry', 'Dishwasher'],
    description: 'Room in a renovated Heights townhome. Great neighborhood for biking and walking.',
    available: true,
    hostId: '14',
    hostName: 'Daniel Moore',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'male', onApp: true, userId: '14' },
      { gender: 'female', onApp: false },
    ],
    walkScore: 78,
  },
  {
    id: '39',
    title: 'Midtown Atlanta High-Rise',
    price: 2300,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    address: '1010 Peachtree St NE',
    city: getCityFromNeighborhood('Midtown Atlanta') || 'Atlanta',
    state: getStateFromNeighborhood('Midtown Atlanta') || 'GA',
    neighborhood: 'Midtown Atlanta',
    coordinates: getCoordinatesFromNeighborhood('Midtown Atlanta') || undefined,
    photos: ['https://picsum.photos/800/600?random=3019'],
    amenities: ['Gym', 'Pool', 'Doorman', 'Parking', 'Concierge'],
    description: 'Modern high-rise living in the heart of Midtown. Walk to Piedmont Park and the Beltline.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 92,
  },
  {
    id: '40',
    title: 'Inman Park Victorian',
    price: 1800,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    address: '885 Euclid Ave NE',
    city: getCityFromNeighborhood('Inman Park') || 'Atlanta',
    state: getStateFromNeighborhood('Inman Park') || 'GA',
    neighborhood: 'Inman Park',
    coordinates: getCoordinatesFromNeighborhood('Inman Park') || undefined,
    photos: ['https://picsum.photos/800/600?random=3020'],
    amenities: ['Backyard', 'Hardwood Floors', 'Pet Friendly', 'Laundry'],
    description: 'Beautiful Victorian home on the Beltline. Walkable to Krog Street Market and Ponce City Market.',
    available: true,
    hostId: '11',
    hostName: 'Sophia Brown',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 88,
  },
  {
    id: '41',
    title: 'Downtown LA Loft',
    price: 2500,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    address: '645 S Los Angeles St',
    city: getCityFromNeighborhood('Downtown LA') || 'Los Angeles',
    state: getStateFromNeighborhood('Downtown LA') || 'CA',
    neighborhood: 'Downtown LA',
    coordinates: getCoordinatesFromNeighborhood('Downtown LA') || undefined,
    photos: ['https://picsum.photos/800/600?random=3021'],
    amenities: ['Gym', 'Rooftop Deck', 'Doorman', 'In-Unit Laundry'],
    description: 'Industrial-chic loft in the Historic Core. Walk to Grand Central Market and The Broad.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 94,
  },
  {
    id: '42',
    title: 'Logan Square Garden Unit',
    price: 1400,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 950,
    address: '2312 N Milwaukee Ave',
    city: getCityFromNeighborhood('Logan Square') || 'Chicago',
    state: getStateFromNeighborhood('Logan Square') || 'IL',
    neighborhood: 'Logan Square',
    coordinates: getCoordinatesFromNeighborhood('Logan Square') || undefined,
    photos: ['https://picsum.photos/800/600?random=3022'],
    amenities: ['Backyard', 'In-Unit Laundry', 'Pet Friendly', 'Storage'],
    description: 'Garden unit with private patio in Logan Square. Near the 606 trail and great restaurants.',
    available: true,
    hostId: '10',
    hostName: 'Ryan Garcia',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 91,
  },
  {
    id: '43',
    title: 'Wynwood Arts District Studio',
    price: 1600,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    address: '250 NW 24th St',
    city: getCityFromNeighborhood('Wynwood') || 'Miami',
    state: getStateFromNeighborhood('Wynwood') || 'FL',
    neighborhood: 'Wynwood',
    coordinates: getCoordinatesFromNeighborhood('Wynwood') || undefined,
    photos: ['https://picsum.photos/800/600?random=3023'],
    amenities: ['Central AC', 'Hardwood Floors', 'Elevator'],
    description: 'Creative studio in the heart of Wynwood Walls. Surrounded by galleries and street art.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: false,
    propertyType: 'sublet',
    roomType: 'entire',
    walkScore: 90,
  },
  {
    id: '44',
    title: 'SOMA Tech Pad',
    price: 3000,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    address: '888 Brannan St',
    city: getCityFromNeighborhood('SOMA') || 'San Francisco',
    state: getStateFromNeighborhood('SOMA') || 'CA',
    neighborhood: 'SOMA',
    coordinates: getCoordinatesFromNeighborhood('SOMA') || undefined,
    photos: ['https://picsum.photos/800/600?random=3024'],
    amenities: ['Gym', 'Doorman', 'In-Unit Laundry', 'Parking'],
    description: 'Modern apartment near tech offices and Oracle Park. Premium finishes and amenities.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 93,
  },
  {
    id: '45',
    title: 'Zilker Park Cottage',
    price: 1900,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 800,
    address: '1100 Barton Springs Rd',
    city: getCityFromNeighborhood('Zilker') || 'Austin',
    state: getStateFromNeighborhood('Zilker') || 'TX',
    neighborhood: 'Zilker',
    coordinates: getCoordinatesFromNeighborhood('Zilker') || undefined,
    photos: ['https://picsum.photos/800/600?random=3025'],
    amenities: ['Backyard', 'Parking', 'Pet Friendly', 'Central AC'],
    description: 'Adorable cottage steps from Barton Springs Pool and Zilker Park. Live music nearby.',
    available: true,
    hostId: '9',
    hostName: 'Amanda Lee',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 80,
  },
  {
    id: '46',
    title: 'Queen Anne View Apartment',
    price: 2200,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    address: '501 Queen Anne Ave N',
    city: getCityFromNeighborhood('Queen Anne') || 'Seattle',
    state: getStateFromNeighborhood('Queen Anne') || 'WA',
    neighborhood: 'Queen Anne',
    coordinates: getCoordinatesFromNeighborhood('Queen Anne') || undefined,
    photos: ['https://picsum.photos/800/600?random=3026'],
    amenities: ['Elevator', 'Laundry', 'Storage'],
    description: 'Apartment with sweeping views of the Space Needle and Puget Sound. Quiet residential neighborhood.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 86,
  },
  {
    id: '47',
    title: 'LoDo Downtown Denver',
    price: 2600,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    address: '1735 19th St',
    city: getCityFromNeighborhood('LoDo') || 'Denver',
    state: getStateFromNeighborhood('LoDo') || 'CO',
    neighborhood: 'LoDo',
    coordinates: getCoordinatesFromNeighborhood('LoDo') || undefined,
    photos: ['https://picsum.photos/800/600?random=3027'],
    amenities: ['Gym', 'Rooftop Deck', 'Parking', 'Concierge', 'In-Unit Laundry'],
    description: 'Upscale condo in Lower Downtown. Walk to Coors Field and Union Station.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 95,
  },
  {
    id: '48',
    title: 'South End Duplex Room',
    price: 1300,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    address: '48 Tremont St',
    city: getCityFromNeighborhood('South End') || 'Boston',
    state: getStateFromNeighborhood('South End') || 'MA',
    neighborhood: 'South End',
    coordinates: getCoordinatesFromNeighborhood('South End') || undefined,
    photos: ['https://picsum.photos/800/600?random=3028'],
    amenities: ['Hardwood Floors', 'Backyard', 'Laundry', 'Dishwasher'],
    description: 'Room in a beautiful South End duplex. Near SoWa Market and the best restaurants in Boston.',
    available: true,
    hostId: '8',
    hostName: 'Ryan Thompson',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'male', onApp: true, userId: '8' },
      { gender: 'female', onApp: false },
    ],
    walkScore: 94,
  },
  {
    id: '49',
    title: 'Buckhead Luxury Suite',
    price: 2800,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    address: '3455 Peachtree Rd NE',
    city: getCityFromNeighborhood('Buckhead') || 'Atlanta',
    state: getStateFromNeighborhood('Buckhead') || 'GA',
    neighborhood: 'Buckhead',
    coordinates: getCoordinatesFromNeighborhood('Buckhead') || undefined,
    photos: ['https://picsum.photos/800/600?random=3029'],
    amenities: ['Gym', 'Pool', 'Concierge', 'Parking', 'Elevator'],
    description: 'Luxury living in Buckhead with access to Lenox Square and Phipps Plaza.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 76,
  },
  {
    id: '50',
    title: 'Rice Village Apartment',
    price: 1500,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    address: '2500 University Blvd',
    city: getCityFromNeighborhood('Rice Village') || 'Houston',
    state: getStateFromNeighborhood('Rice Village') || 'TX',
    neighborhood: 'Rice Village',
    coordinates: getCoordinatesFromNeighborhood('Rice Village') || undefined,
    photos: ['https://picsum.photos/800/600?random=3030'],
    amenities: ['Central AC', 'Parking', 'Laundry', 'Pool'],
    description: 'Well-maintained apartment near Rice University. Great dining and shopping in the Village.',
    available: true,
    hostId: '10',
    hostName: 'Ryan Garcia',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 84,
  },
];

export const extraGroups: Group[] = [
  {
    id: '16',
    name: 'Nurses & Healthcare Workers',
    description: 'Healthcare professionals who understand shift work and need a quiet, supportive home',
    members: ['5', '13'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2000,
    preferredLocation: 'Brickell',
    createdAt: new Date('2024-04-25'),
    createdBy: '5',
  },
  {
    id: '17',
    name: 'Teachers United',
    description: 'Educators looking for affordable housing near schools and transit',
    members: ['4'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1600,
    preferredLocation: 'Lincoln Park',
    createdAt: new Date('2024-04-28'),
    createdBy: '4',
  },
  {
    id: '18',
    name: 'LGBTQ+ Friendly Housing',
    description: 'Inclusive and welcoming living environment for the LGBTQ+ community',
    members: ['11', '22'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2400,
    preferredLocation: 'Castro',
    createdAt: new Date('2024-05-01'),
    createdBy: '11',
  },
  {
    id: '19',
    name: 'International Students',
    description: 'Students from abroad looking for community and affordable shared housing',
    members: ['26'],
    pendingMembers: [],
    maxMembers: 5,
    budget: 1200,
    preferredLocation: 'Cambridge',
    createdAt: new Date('2024-05-05'),
    createdBy: '26',
  },
  {
    id: '20',
    name: 'Vegan & Plant-Based Living',
    description: 'Plant-based eaters seeking a cruelty-free kitchen and conscious living space',
    members: ['3', '17'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1800,
    preferredLocation: 'Silver Lake',
    createdAt: new Date('2024-05-08'),
    createdBy: '3',
  },
  {
    id: '21',
    name: 'Gamers Den',
    description: 'Gamers and streamers who need fast internet and a setup-friendly space',
    members: ['6', '16'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1500,
    preferredLocation: 'East Austin',
    createdAt: new Date('2024-05-10'),
    createdBy: '6',
  },
  {
    id: '22',
    name: 'Book Lovers Collective',
    description: 'Readers and writers who enjoy quiet evenings and literary discussions',
    members: ['15'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1700,
    preferredLocation: 'Back Bay',
    createdAt: new Date('2024-05-12'),
    createdBy: '15',
  },
  {
    id: '23',
    name: 'Sports Fans House',
    description: 'Sports enthusiasts looking for roommates to watch games and stay active',
    members: ['2', '14'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2200,
    preferredLocation: 'Lakeview',
    createdAt: new Date('2024-05-15'),
    createdBy: '2',
  },
  {
    id: '24',
    name: 'Single Parents Support',
    description: 'Single parents seeking family-friendly shared housing with mutual support',
    members: [],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1400,
    preferredLocation: 'The Heights Houston',
    createdAt: new Date('2024-05-18'),
    createdBy: '9',
  },
  {
    id: '25',
    name: 'Night Shift Workers',
    description: 'Professionals working overnight shifts who need daytime quiet and understanding roommates',
    members: ['5'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1600,
    preferredLocation: 'Montrose',
    createdAt: new Date('2024-05-20'),
    createdBy: '5',
  },
  {
    id: '26',
    name: 'Minimalist Dwellers',
    description: 'Less is more. Simple living with minimal clutter and shared values',
    members: ['1'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2000,
    preferredLocation: 'RiNo',
    createdAt: new Date('2024-05-22'),
    createdBy: '1',
  },
  {
    id: '27',
    name: 'Denver Outdoor Adventurers',
    description: 'Hikers, skiers, and mountain bikers looking for a basecamp near the Rockies',
    members: ['25'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2300,
    preferredLocation: 'Washington Park',
    createdAt: new Date('2024-05-25'),
    createdBy: '25',
  },
  {
    id: '28',
    name: 'Miami Foodies',
    description: 'Food lovers who enjoy cooking, sharing meals, and exploring restaurants together',
    members: ['24'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2100,
    preferredLocation: 'Wynwood',
    createdAt: new Date('2024-05-28'),
    createdBy: '24',
  },
  {
    id: '29',
    name: 'ATL Creatives',
    description: 'Artists, musicians, and creators looking for an inspiring shared space in Atlanta',
    members: ['23'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1800,
    preferredLocation: 'Old Fourth Ward',
    createdAt: new Date('2024-06-01'),
    createdBy: '23',
  },
  {
    id: '30',
    name: 'Startup Founders House',
    description: 'Entrepreneurs and startup founders who thrive in a collaborative live-work environment',
    members: ['8', '22'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 3000,
    preferredLocation: 'SOMA',
    createdAt: new Date('2024-06-05'),
    createdBy: '8',
  },
];

export const extraApplications: Application[] = [
  {
    id: '3',
    propertyId: '25',
    propertyTitle: 'Brickell Luxury Condo',
    applicantId: '24',
    applicantName: 'Valentina Cruz',
    applicantPhoto: 'https://picsum.photos/100/100?random=240',
    status: 'pending',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
    message: 'Marine biologist relocating to Miami. I have excellent references and a stable income.',
  },
  {
    id: '4',
    propertyId: '27',
    propertyTitle: 'Mission District Flat',
    applicantId: '22',
    applicantName: 'Priya Sharma',
    applicantPhoto: 'https://picsum.photos/100/100?random=220',
    status: 'approved',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
    message: 'UX researcher at a local startup. Love the neighborhood and can move in immediately.',
  },
  {
    id: '5',
    propertyId: '31',
    propertyTitle: 'Capitol Hill Seattle Apartment',
    applicantId: '25',
    applicantName: 'Jason Nakamura',
    applicantPhoto: 'https://picsum.photos/100/100?random=250',
    status: 'pending',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    message: 'DevOps engineer working remotely. Quiet tenant with great credit history.',
  },
  {
    id: '6',
    propertyId: '35',
    propertyTitle: 'Back Bay Brownstone',
    applicantId: '26',
    applicantName: 'Aisha Mohammed',
    applicantPhoto: 'https://picsum.photos/100/100?random=260',
    status: 'rejected',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10),
    message: 'Graduate student at Harvard. Looking for a quiet and safe living environment.',
  },
  {
    id: '7',
    propertyId: '23',
    propertyTitle: 'Wicker Park Loft',
    applicantId: '23',
    applicantName: 'Terrence Brooks',
    applicantPhoto: 'https://picsum.photos/100/100?random=230',
    status: 'approved',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    message: 'Comedian and bartender in the area. Very clean and respectful of shared spaces.',
  },
  {
    id: '8',
    propertyId: '39',
    propertyTitle: 'Midtown Atlanta High-Rise',
    applicantId: '11',
    applicantName: 'Sophia Brown',
    applicantPhoto: 'https://picsum.photos/100/100?random=11',
    status: 'pending',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24),
    message: 'Relocating to Atlanta for work. Looking for a modern space with great amenities.',
  },
  {
    id: '9',
    propertyId: '29',
    propertyTitle: 'East Austin Modern Home',
    applicantId: '4',
    applicantName: 'Bob Anderson',
    applicantPhoto: 'https://picsum.photos/100/100?random=4',
    status: 'pending',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 48),
    message: 'Teacher moving to Austin. Love the music scene and the neighborhood vibe.',
  },
  {
    id: '10',
    propertyId: '33',
    propertyTitle: 'RiNo Loft',
    applicantId: '12',
    applicantName: 'Matthew Davis',
    applicantPhoto: 'https://picsum.photos/100/100?random=12',
    status: 'rejected',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8),
    message: 'Young professional interested in the RiNo art scene. Ready to sign a lease today.',
  },
];
