import { RoommateProfile } from '../types/models';

export const extraProfiles: RoommateProfile[] = [
  {
    id: '127',
    name: 'Darius Washington',
    age: 29,
    zodiacSign: 'Aries',
    gender: 'male',
    bio: 'Software architect who loves trail running and craft coffee. Looking for a clean, respectful roommate in NYC.',
    occupation: 'Software Architect',
    budget: 2400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1270',
      'https://picsum.photos/400/500?random=1271',
      'https://picsum.photos/400/500?random=1272',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Chelsea',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'linkedin' },
    },
    compatibility: 92,
  },
  {
    id: '128',
    name: 'Priya Sharma',
    age: 26,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Data scientist and amateur painter. Quiet during the week, social on weekends. Love exploring new restaurants.',
    occupation: 'Data Scientist',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1280',
      'https://picsum.photos/400/500?random=1281',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'East Village',
      moveInDate: '06/15/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-20') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-22') },
    },
    compatibility: 87,
  },
  {
    id: '129',
    name: 'Tomás Reyes',
    age: 31,
    zodiacSign: 'Leo',
    gender: 'male',
    bio: 'Chef at a Michelin-rated restaurant. Early riser, love cooking for friends. Very tidy kitchen habits.',
    occupation: 'Chef',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1290',
      'https://picsum.photos/400/500?random=1291',
      'https://picsum.photos/400/500?random=1292',
      'https://picsum.photos/400/500?random=1293',
    ],
    lifestyle: {
      cleanliness: 10,
      socialLevel: 7,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Astoria',
      moveInDate: '05/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-10') },
    },
    compatibility: 78,
  },
  {
    id: '130',
    name: 'Aaliyah Brooks',
    age: 24,
    zodiacSign: 'Gemini',
    gender: 'female',
    bio: 'Graduate student in public health. Enjoy yoga, journaling, and farmers markets. Prefer a calm living space.',
    occupation: 'Graduate Student',
    budget: 1200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1300',
      'https://picsum.photos/400/500?random=1301',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 4,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Crown Heights',
      moveInDate: '08/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-06'), platform: 'instagram' },
    },
    compatibility: 81,
  },
  {
    id: '131',
    name: 'Finn O\'Brien',
    age: 28,
    zodiacSign: 'Sagittarius',
    gender: 'male',
    bio: 'Bartender and aspiring screenwriter. Night owl who keeps things neat. Love live comedy and vinyl records.',
    occupation: 'Bartender',
    budget: 1400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1310',
      'https://picsum.photos/400/500?random=1311',
      'https://picsum.photos/400/500?random=1312',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 8,
      workSchedule: 'Shifts',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'West Village',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-15') },
    },
    compatibility: 65,
  },
  {
    id: '132',
    name: 'Mei-Ling Chen',
    age: 27,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'UX researcher who loves bouldering and board game nights. Organized and communicative roommate.',
    occupation: 'UX Researcher',
    budget: 2000,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1320',
      'https://picsum.photos/400/500?random=1321',
      'https://picsum.photos/400/500?random=1322',
      'https://picsum.photos/400/500?random=1323',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Greenpoint',
      moveInDate: '07/15/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'linkedin' },
    },
    compatibility: 94,
  },
  {
    id: '133',
    name: 'Jordan Rivera',
    age: 33,
    zodiacSign: 'Taurus',
    gender: 'other',
    bio: 'Nonprofit director passionate about community gardening. Calm, respectful, and love a good home-cooked meal.',
    occupation: 'Nonprofit Director',
    budget: 1700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1330',
      'https://picsum.photos/400/500?random=1331',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Tribeca',
      moveInDate: '05/15/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-12') },
    },
    compatibility: 73,
  },
  {
    id: '134',
    name: 'Zara Okafor',
    age: 25,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Fashion designer working in DTLA. Creative, tidy, and always down for a spontaneous road trip.',
    occupation: 'Fashion Designer',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1340',
      'https://picsum.photos/400/500?random=1341',
      'https://picsum.photos/400/500?random=1342',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Downtown LA',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-12') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-11'), platform: 'instagram' },
    },
    compatibility: 88,
  },
  {
    id: '135',
    name: 'Marcus Liu',
    age: 30,
    zodiacSign: 'Aquarius',
    gender: 'male',
    bio: 'Film editor who surfs on weekends. Mellow vibe, keep common areas spotless. Love documentaries and tacos.',
    occupation: 'Film Editor',
    budget: 2200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1350',
      'https://picsum.photos/400/500?random=1351',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 4,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Venice',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-25') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-27') },
    },
    compatibility: 76,
  },
  {
    id: '136',
    name: 'Jasmine Patel',
    age: 27,
    zodiacSign: 'Libra',
    gender: 'female',
    bio: 'Pediatric nurse with a love for hiking and photography. Early riser, clean, and considerate.',
    occupation: 'Pediatric Nurse',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1360',
      'https://picsum.photos/400/500?random=1361',
      'https://picsum.photos/400/500?random=1362',
      'https://picsum.photos/400/500?random=1363',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Echo Park',
      moveInDate: '06/15/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
    },
    compatibility: 91,
  },
  {
    id: '137',
    name: 'Elijah Morales',
    age: 35,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Music producer working from my home studio. Respectful of quiet hours. Big into vinyl and meditation.',
    occupation: 'Music Producer',
    budget: 2500,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1370',
      'https://picsum.photos/400/500?random=1371',
      'https://picsum.photos/400/500?random=1372',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 3,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Los Feliz',
      moveInDate: '05/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-20') },
    },
    compatibility: 68,
  },
  {
    id: '138',
    name: 'Sofia Castillo',
    age: 23,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Art gallery assistant and part-time ceramics teacher. Love sunset walks and plant care.',
    occupation: 'Gallery Assistant',
    budget: 1300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1380',
      'https://picsum.photos/400/500?random=1381',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Flexible',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Koreatown',
      moveInDate: '07/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    compatibility: 72,
  },
  {
    id: '139',
    name: 'Kwame Asante',
    age: 29,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Aerospace engineer who cycles to work. Neat, organized, and enjoy cooking West African cuisine.',
    occupation: 'Aerospace Engineer',
    budget: 2800,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1390',
      'https://picsum.photos/400/500?random=1391',
      'https://picsum.photos/400/500?random=1392',
      'https://picsum.photos/400/500?random=1393',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'West Hollywood',
      moveInDate: '08/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-15') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-17') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-16'), platform: 'linkedin' },
    },
    compatibility: 95,
  },
  {
    id: '140',
    name: 'Nadia Volkov',
    age: 26,
    zodiacSign: 'Aries',
    gender: 'female',
    bio: 'Yoga instructor and freelance illustrator. Peaceful energy, love herbal tea and morning meditation.',
    occupation: 'Yoga Instructor',
    budget: 1100,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1400',
      'https://picsum.photos/400/500?random=1401',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Flexible',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Silver Lake',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-05') },
    },
    compatibility: 70,
  },
  {
    id: '141',
    name: 'Derek Williamson',
    age: 32,
    zodiacSign: 'Gemini',
    gender: 'male',
    bio: 'Investment banker transitioning to fintech. Organized, quiet, and enjoy weekend basketball leagues.',
    occupation: 'Fintech Analyst',
    budget: 3200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1410',
      'https://picsum.photos/400/500?random=1411',
      'https://picsum.photos/400/500?random=1412',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Lincoln Park',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'linkedin' },
    },
    compatibility: 89,
  },
  {
    id: '142',
    name: 'Hannah Kowalski',
    age: 25,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Social worker passionate about community development. Love cooking Polish food and reading fiction.',
    occupation: 'Social Worker',
    budget: 1400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1420',
      'https://picsum.photos/400/500?random=1421',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Wicker Park',
      moveInDate: '06/15/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-20') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-22') },
    },
    compatibility: 82,
  },
  {
    id: '143',
    name: 'Andre Jackson',
    age: 28,
    zodiacSign: 'Leo',
    gender: 'male',
    bio: 'Stand-up comedian and podcast host. Clean, funny, and always have snacks. Night owl but respectful.',
    occupation: 'Comedian',
    budget: 1300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1430',
      'https://picsum.photos/400/500?random=1431',
      'https://picsum.photos/400/500?random=1432',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 9,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Logan Square',
      moveInDate: '05/15/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-15') },
    },
    compatibility: 67,
  },
  {
    id: '144',
    name: 'Yuki Tanaka',
    age: 30,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Veterinarian who loves animals. Quiet, organized, and enjoy making sushi at home. Looking for pet-friendly roommate.',
    occupation: 'Veterinarian',
    budget: 1900,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1440',
      'https://picsum.photos/400/500?random=1441',
      'https://picsum.photos/400/500?random=1442',
      'https://picsum.photos/400/500?random=1443',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 3,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Lakeview',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-06'), platform: 'instagram' },
    },
    compatibility: 90,
  },
  {
    id: '145',
    name: 'Miguel Santos',
    age: 34,
    zodiacSign: 'Sagittarius',
    gender: 'male',
    bio: 'Freelance photographer capturing Chicago architecture. Early bird, neat freak, and love deep dish pizza.',
    occupation: 'Photographer',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1450',
      'https://picsum.photos/400/500?random=1451',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'River North',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-15') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-17') },
    },
    compatibility: 75,
  },
  {
    id: '146',
    name: 'Bianca Torres',
    age: 22,
    zodiacSign: 'Taurus',
    gender: 'female',
    bio: 'Marketing intern at a tech startup. Love thrift shopping, coffee shops, and vintage vinyl.',
    occupation: 'Marketing Intern',
    budget: 1100,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1460',
      'https://picsum.photos/400/500?random=1461',
      'https://picsum.photos/400/500?random=1462',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'West Loop',
      moveInDate: '08/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    compatibility: 63,
  },
  {
    id: '147',
    name: 'Isaiah Thompson',
    age: 27,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Physical therapist and marathon runner. Disciplined, tidy, and love meal prepping on Sundays.',
    occupation: 'Physical Therapist',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1470',
      'https://picsum.photos/400/500?random=1471',
      'https://picsum.photos/400/500?random=1472',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Hyde Park',
      moveInDate: '06/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-12') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-11'), platform: 'linkedin' },
    },
    compatibility: 86,
  },
  {
    id: '148',
    name: 'Valentina Diaz',
    age: 26,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Marine biologist who loves the ocean. Beach volleyball on weekends, always have fresh flowers at home.',
    occupation: 'Marine Biologist',
    budget: 2000,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1480',
      'https://picsum.photos/400/500?random=1481',
      'https://picsum.photos/400/500?random=1482',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'South Beach',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'instagram' },
    },
    compatibility: 93,
  },
  {
    id: '149',
    name: 'Carlos Mendez',
    age: 31,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Real estate agent who knows every corner of Miami. Organized, social, and make amazing Cuban coffee.',
    occupation: 'Real Estate Agent',
    budget: 2400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1490',
      'https://picsum.photos/400/500?random=1491',
      'https://picsum.photos/400/500?random=1492',
      'https://picsum.photos/400/500?random=1493',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 8,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Brickell',
      moveInDate: '06/15/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-20') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-22') },
    },
    compatibility: 84,
  },
  {
    id: '150',
    name: 'Camille Beaumont',
    age: 24,
    zodiacSign: 'Gemini',
    gender: 'female',
    bio: 'Art curator at a contemporary gallery. Enjoy salsa dancing, wine tasting, and gallery openings.',
    occupation: 'Art Curator',
    budget: 1700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1500',
      'https://picsum.photos/400/500?random=1501',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 8,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Wynwood',
      moveInDate: '05/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-10') },
    },
    compatibility: 71,
  },
  {
    id: '151',
    name: 'Rashid Ali',
    age: 29,
    zodiacSign: 'Aries',
    gender: 'male',
    bio: 'Cybersecurity analyst who plays chess competitively. Quiet, disciplined, and enjoy grilling on weekends.',
    occupation: 'Cybersecurity Analyst',
    budget: 2100,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1510',
      'https://picsum.photos/400/500?random=1511',
      'https://picsum.photos/400/500?random=1512',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 3,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Coconut Grove',
      moveInDate: '07/15/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-06'), platform: 'linkedin' },
    },
    compatibility: 87,
  },
  {
    id: '152',
    name: 'Lucia Fernandez',
    age: 33,
    zodiacSign: 'Leo',
    gender: 'female',
    bio: 'Immigration attorney and avid paddleboarder. Value honesty, cleanliness, and good conversation.',
    occupation: 'Immigration Attorney',
    budget: 2600,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1520',
      'https://picsum.photos/400/500?random=1521',
      'https://picsum.photos/400/500?random=1522',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Coral Gables',
      moveInDate: '06/01/2025',
      bedrooms: 3,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-25') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-27') },
    },
    compatibility: 79,
  },
  {
    id: '153',
    name: 'Dante Williams',
    age: 22,
    zodiacSign: 'Aquarius',
    gender: 'male',
    bio: 'DJ and music event promoter. Creative, energetic, and know all the best spots in Miami.',
    occupation: 'DJ',
    budget: 1200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1530',
      'https://picsum.photos/400/500?random=1531',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 10,
      workSchedule: 'Shifts',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'Downtown Miami',
      moveInDate: '05/15/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    compatibility: 58,
  },
  {
    id: '154',
    name: 'Amara Osei',
    age: 28,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Dental hygienist who loves baking sourdough and tending to houseplants. Quiet and considerate roommate.',
    occupation: 'Dental Hygienist',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1540',
      'https://picsum.photos/400/500?random=1541',
      'https://picsum.photos/400/500?random=1542',
      'https://picsum.photos/400/500?random=1543',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Little Havana',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
    },
    compatibility: 83,
  },
  {
    id: '155',
    name: 'Oscar Gutierrez',
    age: 36,
    zodiacSign: 'Taurus',
    gender: 'male',
    bio: 'Architect specializing in sustainable design. Calm presence, enjoy sketching and visiting museums.',
    occupation: 'Architect',
    budget: 3000,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1550',
      'https://picsum.photos/400/500?random=1551',
      'https://picsum.photos/400/500?random=1552',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 4,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Design District',
      moveInDate: '08/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-12') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-11'), platform: 'linkedin' },
    },
    compatibility: 91,
  },
  {
    id: '156',
    name: 'Suki Nakamura',
    age: 27,
    zodiacSign: 'Libra',
    gender: 'female',
    bio: 'Full-stack developer and rock climbing enthusiast. Clean, quiet, and always up for trying new ramen spots.',
    occupation: 'Full-Stack Developer',
    budget: 2800,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1560',
      'https://picsum.photos/400/500?random=1561',
      'https://picsum.photos/400/500?random=1562',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Mission District',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'linkedin' },
    },
    compatibility: 96,
  },
  {
    id: '157',
    name: 'Ryan Gallagher',
    age: 30,
    zodiacSign: 'Sagittarius',
    gender: 'male',
    bio: 'Biotech researcher and weekend sailor. Methodical, clean, and love hosting brunch for friends.',
    occupation: 'Biotech Researcher',
    budget: 2500,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1570',
      'https://picsum.photos/400/500?random=1571',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Marina District',
      moveInDate: '06/15/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-20') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-22') },
    },
    compatibility: 85,
  },
  {
    id: '158',
    name: 'Lila Nair',
    age: 25,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'PhD candidate in computer science. Love late-night coding, matcha lattes, and Golden Gate Park walks.',
    occupation: 'PhD Student',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1580',
      'https://picsum.photos/400/500?random=1581',
      'https://picsum.photos/400/500?random=1582',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 4,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'SOMA',
      moveInDate: '08/15/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
    },
    compatibility: 78,
  },
  {
    id: '159',
    name: 'Nikolai Petrov',
    age: 34,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Senior product manager at a SaaS company. Minimalist, organized, and train for triathlons.',
    occupation: 'Senior Product Manager',
    budget: 3500,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1590',
      'https://picsum.photos/400/500?random=1591',
      'https://picsum.photos/400/500?random=1592',
      'https://picsum.photos/400/500?random=1593',
    ],
    lifestyle: {
      cleanliness: 10,
      socialLevel: 3,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Pacific Heights SF',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'linkedin' },
    },
    compatibility: 88,
  },
  {
    id: '160',
    name: 'Ava Chang',
    age: 23,
    zodiacSign: 'Aries',
    gender: 'female',
    bio: 'Barista and aspiring sommelier. Love discovering hole-in-the-wall restaurants and weekend farmers markets.',
    occupation: 'Barista',
    budget: 1300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1600',
      'https://picsum.photos/400/500?random=1601',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Haight-Ashbury',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-10') },
    },
    compatibility: 64,
  },
  {
    id: '161',
    name: 'Ellis Cooper',
    age: 29,
    zodiacSign: 'Gemini',
    gender: 'other',
    bio: 'Environmental engineer and urban gardener. Composting enthusiast, love making smoothies and reading sci-fi.',
    occupation: 'Environmental Engineer',
    budget: 2200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1610',
      'https://picsum.photos/400/500?random=1611',
      'https://picsum.photos/400/500?random=1612',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Hybrid',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Noe Valley',
      moveInDate: '07/15/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-12') },
    },
    compatibility: 80,
  },
  {
    id: '162',
    name: 'Kendrick Hayes',
    age: 28,
    zodiacSign: 'Leo',
    gender: 'male',
    bio: 'Session musician and guitar teacher. Chill vibes, clean common areas, and love jamming on the porch.',
    occupation: 'Musician',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1620',
      'https://picsum.photos/400/500?random=1621',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Castro',
      moveInDate: '05/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-10-25') },
    },
    compatibility: 69,
  },
  {
    id: '163',
    name: 'Sierra Mitchell',
    age: 26,
    zodiacSign: 'Scorpio',
    gender: 'female',
    bio: 'Marketing strategist for a tech company. Love live music, Austin food trucks, and paddleboarding on Lady Bird Lake.',
    occupation: 'Marketing Strategist',
    budget: 1800,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1630',
      'https://picsum.photos/400/500?random=1631',
      'https://picsum.photos/400/500?random=1632',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'East Austin',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'instagram' },
    },
    compatibility: 92,
  },
  {
    id: '164',
    name: 'Ethan Park',
    age: 31,
    zodiacSign: 'Taurus',
    gender: 'male',
    bio: 'Game developer and competitive gamer. Quiet during work hours, love hosting game nights on weekends.',
    occupation: 'Game Developer',
    budget: 2000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1640',
      'https://picsum.photos/400/500?random=1641',
      'https://picsum.photos/400/500?random=1642',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Downtown Austin',
      moveInDate: '06/15/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-15') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-17') },
    },
    compatibility: 81,
  },
  {
    id: '165',
    name: 'Luna Rodriguez',
    age: 23,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Environmental science student at UT Austin. Love cycling, sustainable living, and weekend brunch.',
    occupation: 'Graduate Student',
    budget: 1100,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1650',
      'https://picsum.photos/400/500?random=1651',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Student',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'South Congress',
      moveInDate: '08/15/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
    },
    compatibility: 74,
  },
  {
    id: '166',
    name: 'Travis Bennett',
    age: 35,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Executive chef running a farm-to-table restaurant. Passionate about cooking, clean kitchen is non-negotiable.',
    occupation: 'Executive Chef',
    budget: 2200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1660',
      'https://picsum.photos/400/500?random=1661',
      'https://picsum.photos/400/500?random=1662',
      'https://picsum.photos/400/500?random=1663',
    ],
    lifestyle: {
      cleanliness: 10,
      socialLevel: 5,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Zilker',
      moveInDate: '06/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
    },
    compatibility: 85,
  },
  {
    id: '167',
    name: 'Reese Kim',
    age: 24,
    zodiacSign: 'Libra',
    gender: 'other',
    bio: 'Graphic designer and mural artist. Creative, easygoing, and always have music playing at home.',
    occupation: 'Graphic Designer',
    budget: 1400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1670',
      'https://picsum.photos/400/500?random=1671',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Hyde Park Austin',
      moveInDate: '07/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-20') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-22') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-21'), platform: 'instagram' },
    },
    compatibility: 77,
  },
  {
    id: '168',
    name: 'Javier Fuentes',
    age: 30,
    zodiacSign: 'Virgo',
    gender: 'male',
    bio: 'Data engineer at a startup. Organized, quiet, and spend weekends at Barton Springs or hiking Greenbelt.',
    occupation: 'Data Engineer',
    budget: 1900,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1680',
      'https://picsum.photos/400/500?random=1681',
      'https://picsum.photos/400/500?random=1682',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 4,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Mueller',
      moveInDate: '06/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-12') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-11'), platform: 'linkedin' },
    },
    compatibility: 90,
  },
  {
    id: '169',
    name: 'Maya Anderson',
    age: 27,
    zodiacSign: 'Gemini',
    gender: 'female',
    bio: 'UX designer at Amazon. Love hiking in the Cascades, specialty coffee, and weekend pottery classes.',
    occupation: 'UX Designer',
    budget: 2200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1690',
      'https://picsum.photos/400/500?random=1691',
      'https://picsum.photos/400/500?random=1692',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Capitol Hill Seattle',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'linkedin' },
    },
    compatibility: 94,
  },
  {
    id: '170',
    name: 'Cole Larsen',
    age: 32,
    zodiacSign: 'Sagittarius',
    gender: 'male',
    bio: 'DevOps engineer and amateur brewer. Clean, quiet, and always experimenting with new IPA recipes.',
    occupation: 'DevOps Engineer',
    budget: 2400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1700',
      'https://picsum.photos/400/500?random=1701',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 5,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Ballard',
      moveInDate: '06/15/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-25') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-27') },
    },
    compatibility: 83,
  },
  {
    id: '171',
    name: 'Iris Nakano',
    age: 25,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Occupational therapist who loves kayaking on Puget Sound. Caring, tidy, and enjoy cooking Japanese food.',
    occupation: 'Occupational Therapist',
    budget: 1700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1710',
      'https://picsum.photos/400/500?random=1711',
      'https://picsum.photos/400/500?random=1712',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Fremont',
      moveInDate: '07/15/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
    },
    compatibility: 87,
  },
  {
    id: '172',
    name: 'Max Sullivan',
    age: 29,
    zodiacSign: 'Aries',
    gender: 'male',
    bio: 'Cloud architect and trail runner. Minimalist lifestyle, enjoy weekend camping trips and craft cocktails.',
    occupation: 'Cloud Architect',
    budget: 2600,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1720',
      'https://picsum.photos/400/500?random=1721',
      'https://picsum.photos/400/500?random=1722',
      'https://picsum.photos/400/500?random=1723',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 4,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Queen Anne',
      moveInDate: '06/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'linkedin' },
    },
    compatibility: 91,
  },
  {
    id: '173',
    name: 'Jade Wu',
    age: 24,
    zodiacSign: 'Scorpio',
    gender: 'female',
    bio: 'Dental student at UW. Study a lot but love exploring Seattle food scene on weekends. Clean and organized.',
    occupation: 'Dental Student',
    budget: 1300,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1730',
      'https://picsum.photos/400/500?random=1731',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'South Lake Union',
      moveInDate: '09/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-15') },
    },
    compatibility: 76,
  },
  {
    id: '174',
    name: 'Rowan Casey',
    age: 33,
    zodiacSign: 'Taurus',
    gender: 'other',
    bio: 'Librarian and avid reader. Quiet, love cats, and enjoy hosting low-key dinner parties with close friends.',
    occupation: 'Librarian',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1740',
      'https://picsum.photos/400/500?random=1741',
      'https://picsum.photos/400/500?random=1742',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 3,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Belltown',
      moveInDate: '07/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-12') },
    },
    compatibility: 72,
  },
  {
    id: '175',
    name: 'Dominic Price',
    age: 28,
    zodiacSign: 'Leo',
    gender: 'male',
    bio: 'Snowboard instructor in winter, personal trainer year-round. Active, outgoing, and keep a clean space.',
    occupation: 'Personal Trainer',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1750',
      'https://picsum.photos/400/500?random=1751',
      'https://picsum.photos/400/500?random=1752',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 8,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'LoDo',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
    },
    compatibility: 79,
  },
  {
    id: '176',
    name: 'Carmen Vasquez',
    age: 26,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Elementary school teacher who loves hiking and craft beer. Organized, friendly, and enjoy Denver sunshine.',
    occupation: 'Teacher',
    budget: 1400,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1760',
      'https://picsum.photos/400/500?random=1761',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 6,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'RiNo',
      moveInDate: '07/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-20') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-22') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-21'), platform: 'instagram' },
    },
    compatibility: 86,
  },
  {
    id: '177',
    name: 'Blake Morrison',
    age: 31,
    zodiacSign: 'Aquarius',
    gender: 'male',
    bio: 'Cannabis industry consultant and mountain biker. Chill, clean, and love Colorado summers.',
    occupation: 'Industry Consultant',
    budget: 2000,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1770',
      'https://picsum.photos/400/500?random=1771',
      'https://picsum.photos/400/500?random=1772',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Flexible',
      pets: false,
      smoking: true,
    },
    preferences: {
      location: 'Capitol Hill Denver',
      moveInDate: '06/15/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-10') },
    },
    compatibility: 66,
  },
  {
    id: '178',
    name: 'Naomi Adler',
    age: 29,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Physician assistant at a Denver hospital. Disciplined, tidy, and love weekend skiing trips.',
    occupation: 'Physician Assistant',
    budget: 2200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1780',
      'https://picsum.photos/400/500?random=1781',
      'https://picsum.photos/400/500?random=1782',
      'https://picsum.photos/400/500?random=1783',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Cherry Creek',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-06'), platform: 'linkedin' },
    },
    compatibility: 93,
  },
  {
    id: '179',
    name: 'Theo Ramirez',
    age: 24,
    zodiacSign: 'Sagittarius',
    gender: 'male',
    bio: 'Brewery assistant and homebrewer. Love dogs, disc golf, and exploring mountain trails.',
    occupation: 'Brewery Assistant',
    budget: 1200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1790',
      'https://picsum.photos/400/500?random=1791',
    ],
    lifestyle: {
      cleanliness: 5,
      socialLevel: 7,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Washington Park',
      moveInDate: '05/15/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    compatibility: 62,
  },
  {
    id: '180',
    name: 'Elena Kozlov',
    age: 32,
    zodiacSign: 'Capricorn',
    gender: 'female',
    bio: 'Environmental lawyer focused on climate policy. Enjoy cross-country skiing, book clubs, and sourdough baking.',
    occupation: 'Environmental Lawyer',
    budget: 2400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1800',
      'https://picsum.photos/400/500?random=1801',
      'https://picsum.photos/400/500?random=1802',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Five Points',
      moveInDate: '08/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-12') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-11'), platform: 'linkedin' },
    },
    compatibility: 88,
  },
  {
    id: '181',
    name: 'Owen Fitzgerald',
    age: 27,
    zodiacSign: 'Taurus',
    gender: 'male',
    bio: 'Postdoc researcher at MIT. Love sailing on the Charles, pub trivia, and nerdy board games.',
    occupation: 'Postdoctoral Researcher',
    budget: 2000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1810',
      'https://picsum.photos/400/500?random=1811',
      'https://picsum.photos/400/500?random=1812',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 6,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Cambridge',
      moveInDate: '09/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
    },
    compatibility: 82,
  },
  {
    id: '182',
    name: 'Sienna McCormick',
    age: 25,
    zodiacSign: 'Leo',
    gender: 'female',
    bio: 'Nurse practitioner at Mass General. Early riser, love running along the Esplanade and exploring new brunch spots.',
    occupation: 'Nurse Practitioner',
    budget: 2200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1820',
      'https://picsum.photos/400/500?random=1821',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Back Bay',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-20') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-22') },
      social_media: { verified: true, verifiedAt: new Date('2024-11-21'), platform: 'instagram' },
    },
    compatibility: 91,
  },
  {
    id: '183',
    name: 'Liam O\'Connor',
    age: 30,
    zodiacSign: 'Gemini',
    gender: 'male',
    bio: 'Craft brewer and history buff. Love exploring old neighborhoods, cooking Irish stew, and watching rugby.',
    occupation: 'Craft Brewer',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1830',
      'https://picsum.photos/400/500?random=1831',
      'https://picsum.photos/400/500?random=1832',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'South Boston',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-15') },
    },
    compatibility: 73,
  },
  {
    id: '184',
    name: 'Anika Johansson',
    age: 28,
    zodiacSign: 'Libra',
    gender: 'female',
    bio: 'Biostatistician at a pharma company. Love yoga, weekend trips to Cape Cod, and hosting dinner parties.',
    occupation: 'Biostatistician',
    budget: 2400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1840',
      'https://picsum.photos/400/500?random=1841',
      'https://picsum.photos/400/500?random=1842',
      'https://picsum.photos/400/500?random=1843',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'South End',
      moveInDate: '07/15/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-06'), platform: 'linkedin' },
    },
    compatibility: 89,
  },
  {
    id: '185',
    name: 'Caleb Washington',
    age: 33,
    zodiacSign: 'Aries',
    gender: 'male',
    bio: 'High school basketball coach and part-time sports writer. Active, disciplined, and love grilling on weekends.',
    occupation: 'Basketball Coach',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1850',
      'https://picsum.photos/400/500?random=1851',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Beacon Hill',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
    },
    compatibility: 75,
  },
  {
    id: '186',
    name: 'Zoe Whitfield',
    age: 22,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Music student at Berklee College. Practice flute daily but always use headphones. Neat and respectful.',
    occupation: 'Music Student',
    budget: 1200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1860',
      'https://picsum.photos/400/500?random=1861',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 5,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Fenway',
      moveInDate: '09/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    compatibility: 68,
  },
  {
    id: '187',
    name: 'Xavier Green',
    age: 29,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Oil and gas engineer transitioning to renewable energy. Quiet, gym regular, and enjoy weekend BBQs.',
    occupation: 'Energy Engineer',
    budget: 1800,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1870',
      'https://picsum.photos/400/500?random=1871',
      'https://picsum.photos/400/500?random=1872',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Midtown Houston',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'linkedin' },
    },
    compatibility: 84,
  },
  {
    id: '188',
    name: 'Destiny Harper',
    age: 26,
    zodiacSign: 'Gemini',
    gender: 'female',
    bio: 'Registered dietitian and meal prep queen. Love cycling, farmers markets, and keeping a spotless kitchen.',
    occupation: 'Registered Dietitian',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1880',
      'https://picsum.photos/400/500?random=1881',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Montrose',
      moveInDate: '06/15/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-25') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-27') },
    },
    compatibility: 87,
  },
  {
    id: '189',
    name: 'Marcus Chen',
    age: 35,
    zodiacSign: 'Leo',
    gender: 'male',
    bio: 'Restaurant owner specializing in fusion cuisine. Busy schedule but love a clean, peaceful home.',
    occupation: 'Restaurant Owner',
    budget: 2500,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1890',
      'https://picsum.photos/400/500?random=1891',
      'https://picsum.photos/400/500?random=1892',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 4,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'The Heights Houston',
      moveInDate: '06/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
    },
    compatibility: 80,
  },
  {
    id: '190',
    name: 'Tessa Morales',
    age: 23,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Medical student at Baylor. Study hard but always make time for yoga and exploring Houston food scene.',
    occupation: 'Medical Student',
    budget: 1100,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1900',
      'https://picsum.photos/400/500?random=1901',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 5,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Museum District',
      moveInDate: '08/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-15') },
    },
    compatibility: 74,
  },
  {
    id: '191',
    name: 'Anton Bridges',
    age: 30,
    zodiacSign: 'Aquarius',
    gender: 'male',
    bio: 'Petroleum engineer who loves astronomy. Have a telescope on the balcony and enjoy stargazing weekends.',
    occupation: 'Petroleum Engineer',
    budget: 2200,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1910',
      'https://picsum.photos/400/500?random=1911',
      'https://picsum.photos/400/500?random=1912',
      'https://picsum.photos/400/500?random=1913',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 3,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Rice Village',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-12') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-11'), platform: 'linkedin' },
    },
    compatibility: 85,
  },
  {
    id: '192',
    name: 'Kira Pham',
    age: 27,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Software QA engineer and plant mom. Quiet, organized, and love exploring Vietnamese restaurants in Houston.',
    occupation: 'QA Engineer',
    budget: 1600,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1920',
      'https://picsum.photos/400/500?random=1921',
      'https://picsum.photos/400/500?random=1922',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'EaDo',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
    },
    compatibility: 90,
  },
  {
    id: '193',
    name: 'Terrence Williams',
    age: 28,
    zodiacSign: 'Sagittarius',
    gender: 'male',
    bio: 'Film producer and cinephile. Love the Atlanta film scene, hiking Stone Mountain, and Southern comfort food.',
    occupation: 'Film Producer',
    budget: 2000,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1930',
      'https://picsum.photos/400/500?random=1931',
      'https://picsum.photos/400/500?random=1932',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Midtown Atlanta',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'instagram' },
    },
    compatibility: 83,
  },
  {
    id: '194',
    name: 'Adrienne Foster',
    age: 31,
    zodiacSign: 'Libra',
    gender: 'female',
    bio: 'Tech recruiter and yoga enthusiast. Love exploring the BeltLine, trying new coffee shops, and weekend brunches.',
    occupation: 'Tech Recruiter',
    budget: 1800,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1940',
      'https://picsum.photos/400/500?random=1941',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 6,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Virginia-Highland',
      moveInDate: '06/15/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-20') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-22') },
    },
    compatibility: 86,
  },
  {
    id: '195',
    name: 'Jaylen Scott',
    age: 25,
    zodiacSign: 'Aries',
    gender: 'male',
    bio: 'Music engineer at a recording studio. Night owl but keep shared spaces immaculate. Love Atlanta hip-hop scene.',
    occupation: 'Music Engineer',
    budget: 1500,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1950',
      'https://picsum.photos/400/500?random=1951',
      'https://picsum.photos/400/500?random=1952',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 8,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Old Fourth Ward',
      moveInDate: '05/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-10') },
    },
    compatibility: 71,
  },
  {
    id: '196',
    name: 'Nia Campbell',
    age: 27,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Public health researcher at CDC. Organized, health-conscious, and love exploring Atlanta farmers markets.',
    occupation: 'Public Health Researcher',
    budget: 1700,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1960',
      'https://picsum.photos/400/500?random=1961',
      'https://picsum.photos/400/500?random=1962',
      'https://picsum.photos/400/500?random=1963',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Inman Park',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-06'), platform: 'linkedin' },
    },
    compatibility: 92,
  },
  {
    id: '197',
    name: 'Phoenix Taylor',
    age: 23,
    zodiacSign: 'Gemini',
    gender: 'other',
    bio: 'Tattoo artist and vegan cook. Creative soul seeking a respectful, open-minded roommate in Atlanta.',
    occupation: 'Tattoo Artist',
    budget: 1200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1970',
      'https://picsum.photos/400/500?random=1971',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Decatur',
      moveInDate: '06/01/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-11-15') },
      government_id: { verified: true, verifiedAt: new Date('2024-11-17') },
    },
    compatibility: 67,
  },
  {
    id: '198',
    name: 'Ezra Mitchell',
    age: 34,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Civil rights attorney and marathon runner. Disciplined, quiet, and value a peaceful home environment.',
    occupation: 'Civil Rights Attorney',
    budget: 2600,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=1980',
      'https://picsum.photos/400/500?random=1981',
      'https://picsum.photos/400/500?random=1982',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 3,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Buckhead',
      moveInDate: '08/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-10') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-12') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-11'), platform: 'linkedin' },
    },
    compatibility: 88,
  },
  {
    id: '199',
    name: 'Harlow Davis',
    age: 21,
    zodiacSign: 'Scorpio',
    gender: 'female',
    bio: 'Georgia Tech engineering student. Love robotics, escape rooms, and late-night study sessions with good snacks.',
    occupation: 'Engineering Student',
    budget: 900,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1990',
      'https://picsum.photos/400/500?random=1991',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Midtown Atlanta',
      moveInDate: '08/15/2025',
      bedrooms: 1,
      bathrooms: 1,
      privateBathroom: false,
    },
    compatibility: 63,
  },
  {
    id: '200',
    name: 'Santiago Herrera',
    age: 38,
    zodiacSign: 'Taurus',
    gender: 'male',
    bio: 'Senior accountant and weekend golfer. Quiet, neat, and prefer a mature roommate who respects shared spaces.',
    occupation: 'Senior Accountant',
    budget: 2000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=2000',
      'https://picsum.photos/400/500?random=2001',
      'https://picsum.photos/400/500?random=2002',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 2,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Upper West Side',
      moveInDate: '07/01/2025',
      bedrooms: 2,
      bathrooms: 2,
      privateBathroom: true,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-01') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-03') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-02'), platform: 'linkedin' },
    },
    compatibility: 77,
  },
  {
    id: '201',
    name: 'Willow Sinclair',
    age: 26,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Interior designer and weekend antiquing enthusiast. Love creating cozy spaces, candle-lit evenings, and fresh flowers.',
    occupation: 'Interior Designer',
    budget: 1900,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=2010',
      'https://picsum.photos/400/500?random=2011',
      'https://picsum.photos/400/500?random=2012',
      'https://picsum.photos/400/500?random=2013',
    ],
    lifestyle: {
      cleanliness: 10,
      socialLevel: 5,
      workSchedule: 'Flexible',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'North Beach SF',
      moveInDate: '06/15/2025',
      bedrooms: 2,
      bathrooms: 1,
      privateBathroom: false,
    },
    verification: {
      phone: { verified: true, verifiedAt: new Date('2024-12-05') },
      government_id: { verified: true, verifiedAt: new Date('2024-12-07') },
      social_media: { verified: true, verifiedAt: new Date('2024-12-06'), platform: 'instagram' },
    },
    compatibility: 95,
  },
];
