import { RoommateProfile, Property, Group, Conversation, Application, User } from '../types/models';

export const mockProfileUsers: User[] = [
  {
    id: '1',
    email: 'sarah.johnson@email.com',
    name: 'Sarah Johnson',
    role: 'renter',
    subscription: { plan: 'vip', status: 'active' },
    boostData: { boostsUsed: 2, isBoosted: true, boostExpiresAt: new Date(Date.now() + 20 * 60 * 60 * 1000), lastBoostDate: new Date() },
  },
  {
    id: '2',
    email: 'michael.chen@email.com',
    name: 'Michael Chen',
    role: 'renter',
    subscription: { plan: 'premium', status: 'active' },
    boostData: { boostsUsed: 1, isBoosted: true, boostExpiresAt: new Date(Date.now() + 10 * 60 * 60 * 1000), lastBoostDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) },
  },
  {
    id: '3',
    email: 'emily.rodriguez@email.com',
    name: 'Emily Rodriguez',
    role: 'renter',
    subscription: { plan: 'free', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
  {
    id: '4',
    email: 'bob.anderson@email.com',
    name: 'Bob Anderson',
    role: 'renter',
    subscription: { plan: 'vip', status: 'active' },
    boostData: { boostsUsed: 5, isBoosted: false },
  },
  {
    id: '5',
    email: 'jessica.park@email.com',
    name: 'Jessica Park',
    role: 'renter',
    subscription: { plan: 'premium', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
  {
    id: '6',
    email: 'david.martinez@email.com',
    name: 'David Martinez',
    role: 'renter',
    subscription: { plan: 'free', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
  {
    id: '7',
    email: 'lisa.thompson@email.com',
    name: 'Lisa Thompson',
    role: 'renter',
    subscription: { plan: 'premium', status: 'active' },
    boostData: { boostsUsed: 1, isBoosted: true, boostExpiresAt: new Date(Date.now() + 5 * 60 * 60 * 1000), lastBoostDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) },
  },
  {
    id: '8',
    email: 'james.wilson@email.com',
    name: 'James Wilson',
    role: 'renter',
    subscription: { plan: 'vip', status: 'active' },
    boostData: { boostsUsed: 3, isBoosted: false },
  },
  {
    id: '9',
    email: 'amanda.lee@email.com',
    name: 'Amanda Lee',
    role: 'renter',
    subscription: { plan: 'free', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
  {
    id: '10',
    email: 'ryan.garcia@email.com',
    name: 'Ryan Garcia',
    role: 'renter',
    subscription: { plan: 'premium', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
  {
    id: '11',
    email: 'sophia.brown@email.com',
    name: 'Sophia Brown',
    role: 'renter',
    subscription: { plan: 'vip', status: 'active' },
    boostData: { boostsUsed: 4, isBoosted: true, boostExpiresAt: new Date(Date.now() + 15 * 60 * 60 * 1000), lastBoostDate: new Date() },
  },
  {
    id: '12',
    email: 'matthew.davis@email.com',
    name: 'Matthew Davis',
    role: 'renter',
    subscription: { plan: 'free', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
  {
    id: '13',
    email: 'olivia.miller@email.com',
    name: 'Olivia Miller',
    role: 'renter',
    subscription: { plan: 'premium', status: 'active' },
    boostData: { boostsUsed: 1, isBoosted: false, lastBoostDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) },
  },
  {
    id: '14',
    email: 'daniel.moore@email.com',
    name: 'Daniel Moore',
    role: 'renter',
    subscription: { plan: 'vip', status: 'active' },
    boostData: { boostsUsed: 6, isBoosted: false },
  },
  {
    id: '15',
    email: 'emma.taylor@email.com',
    name: 'Emma Taylor',
    role: 'renter',
    subscription: { plan: 'free', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
];

export const mockRoommateProfiles: RoommateProfile[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    age: 24,
    bio: 'Software engineer who loves hiking, cooking, and quiet evenings. Looking for a clean and respectful roommate.',
    occupation: 'Software Engineer',
    budget: 1200,
    photos: ['https://picsum.photos/400/500?random=1'],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Downtown',
      moveInDate: '2025-01-01',
      bedrooms: 2,
    },
    compatibility: 92,
  },
  {
    id: '2',
    name: 'Michael Chen',
    age: 26,
    bio: 'Marketing professional, gym enthusiast, and weekend adventurer. Love to host small gatherings!',
    occupation: 'Marketing Manager',
    budget: 1400,
    photos: ['https://picsum.photos/400/500?random=2'],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 9,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Midtown',
      moveInDate: '2025-02-01',
      bedrooms: 2,
    },
    compatibility: 85,
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    age: 23,
    bio: 'Graphic designer working from home. Cat mom, plant lover, and yoga enthusiast.',
    occupation: 'Graphic Designer',
    budget: 1000,
    photos: ['https://picsum.photos/400/500?random=3'],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Westside',
      moveInDate: '2025-01-15',
      bedrooms: 2,
    },
    compatibility: 78,
  },
  {
    id: '4',
    name: 'Bob Anderson',
    age: 27,
    bio: 'Teacher by day, musician by night. Looking for a chill roommate who appreciates good music and great conversations.',
    occupation: 'High School Teacher',
    budget: 1100,
    photos: ['https://picsum.photos/400/500?random=4'],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Downtown',
      moveInDate: '2025-01-10',
      bedrooms: 2,
    },
    compatibility: 88,
  },
  {
    id: '5',
    name: 'Jessica Park',
    age: 25,
    bio: 'Data analyst with a passion for reading and meditation. Enjoys peaceful mornings and weekend brunches.',
    occupation: 'Data Analyst',
    budget: 1300,
    photos: ['https://picsum.photos/400/500?random=5'],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'University Area',
      moveInDate: '2025-01-20',
      bedrooms: 1,
    },
    compatibility: 81,
  },
  {
    id: '6',
    name: 'David Martinez',
    age: 29,
    bio: 'Finance professional who loves running, cooking, and trying new restaurants. Early riser and weekend explorer.',
    occupation: 'Financial Analyst',
    budget: 1600,
    photos: ['https://picsum.photos/400/500?random=6'],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Financial District',
      moveInDate: '2025-02-15',
      bedrooms: 2,
    },
    compatibility: 90,
  },
  {
    id: '7',
    name: 'Amanda White',
    age: 24,
    bio: 'Veterinary assistant and dog lover. Looking for a pet-friendly home with outdoor space.',
    occupation: 'Veterinary Assistant',
    budget: 1050,
    photos: ['https://picsum.photos/400/500?random=7'],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Sunset District',
      moveInDate: '2025-01-25',
      bedrooms: 2,
    },
    compatibility: 76,
  },
  {
    id: '8',
    name: 'Ryan Thompson',
    age: 28,
    bio: 'Web developer working remotely. Coffee enthusiast, gamer, and tech geek. Quiet and focused during work hours.',
    occupation: 'Web Developer',
    budget: 1250,
    photos: ['https://picsum.photos/400/500?random=8'],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 5,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Mission District',
      moveInDate: '2025-02-01',
      bedrooms: 1,
    },
    compatibility: 83,
  },
  {
    id: '9',
    name: 'Olivia Green',
    age: 26,
    bio: 'Environmental scientist passionate about sustainability. Vegan, minimalist, and nature lover.',
    occupation: 'Environmental Scientist',
    budget: 950,
    photos: ['https://picsum.photos/400/500?random=9'],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Noe Valley',
      moveInDate: '2025-01-30',
      bedrooms: 2,
    },
    compatibility: 79,
  },
  {
    id: '10',
    name: 'James Lee',
    age: 30,
    bio: 'Music producer and DJ. Night owl who loves creative projects and collaborative energy.',
    occupation: 'Music Producer',
    budget: 1150,
    photos: ['https://picsum.photos/400/500?random=10'],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 8,
      workSchedule: 'Freelance',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'SOMA',
      moveInDate: '2025-02-10',
      bedrooms: 2,
    },
    compatibility: 72,
  },
  {
    id: '11',
    name: 'Sophia Kim',
    age: 22,
    bio: 'Graduate student studying architecture. Looking for quiet study space and friendly conversation.',
    occupation: 'Graduate Student',
    budget: 800,
    photos: ['https://picsum.photos/400/500?random=11'],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Richmond District',
      moveInDate: '2025-01-05',
      bedrooms: 1,
    },
    compatibility: 85,
  },
  {
    id: '12',
    name: 'Marcus Johnson',
    age: 31,
    bio: 'Personal trainer and nutrition coach. Active lifestyle, early bird, and meal prep enthusiast.',
    occupation: 'Personal Trainer',
    budget: 1200,
    photos: ['https://picsum.photos/400/500?random=12'],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Marina District',
      moveInDate: '2025-02-20',
      bedrooms: 2,
    },
    compatibility: 87,
  },
  {
    id: '13',
    name: 'Isabella Garcia',
    age: 25,
    bio: 'Nurse working rotating shifts. Looking for understanding roommate who respects varied schedules.',
    occupation: 'Registered Nurse',
    budget: 1100,
    photos: ['https://picsum.photos/400/500?random=13'],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Outer Sunset',
      moveInDate: '2025-01-15',
      bedrooms: 2,
    },
    compatibility: 82,
  },
  {
    id: '14',
    name: 'Alex Turner',
    age: 27,
    bio: 'Freelance photographer and travel blogger. Adventurous spirit looking for creative and open-minded roommate.',
    occupation: 'Photographer',
    budget: 1000,
    photos: ['https://picsum.photos/400/500?random=14'],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 8,
      workSchedule: 'Freelance',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Castro',
      moveInDate: '2025-02-05',
      bedrooms: 1,
    },
    compatibility: 80,
  },
  {
    id: '15',
    name: 'Rachel Cohen',
    age: 29,
    bio: 'Attorney with a busy schedule but loves to unwind with wine and good books. Organized and respectful.',
    occupation: 'Attorney',
    budget: 1700,
    photos: ['https://picsum.photos/400/500?random=15'],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Pacific Heights',
      moveInDate: '2025-03-01',
      bedrooms: 2,
    },
    compatibility: 91,
  },
  {
    id: '16',
    name: 'Kevin Patel',
    age: 23,
    bio: 'Software engineering intern learning and growing. Gamer, coder, and pizza connoisseur.',
    occupation: 'Software Engineering Intern',
    budget: 900,
    photos: ['https://picsum.photos/400/500?random=16'],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'SoMa',
      moveInDate: '2025-01-12',
      bedrooms: 1,
    },
    compatibility: 77,
  },
  {
    id: '17',
    name: 'Maya Williams',
    age: 26,
    bio: 'Social media manager who works from cafes. Love plants, journaling, and afternoon yoga sessions.',
    occupation: 'Social Media Manager',
    budget: 1150,
    photos: ['https://picsum.photos/400/500?random=17'],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Hayes Valley',
      moveInDate: '2025-02-12',
      bedrooms: 2,
    },
    compatibility: 84,
  },
  {
    id: '18',
    name: 'Chris Davis',
    age: 32,
    bio: 'Chef with irregular hours. Passionate about cooking and sharing meals. Clean kitchen is a must!',
    occupation: 'Chef',
    budget: 1300,
    photos: ['https://picsum.photos/400/500?random=18'],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 8,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'North Beach',
      moveInDate: '2025-01-28',
      bedrooms: 2,
    },
    compatibility: 86,
  },
  {
    id: '19',
    name: 'Natalie Brown',
    age: 24,
    bio: 'Aspiring writer working on my first novel. Quiet, introverted, but enjoy meaningful conversations.',
    occupation: 'Barista',
    budget: 850,
    photos: ['https://picsum.photos/400/500?random=19'],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 4,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Inner Richmond',
      moveInDate: '2025-02-08',
      bedrooms: 1,
    },
    compatibility: 75,
  },
  {
    id: '20',
    name: 'Daniel Scott',
    age: 28,
    bio: 'Product manager in tech. Balanced lifestyle with work and play. Board game nights are my favorite!',
    occupation: 'Product Manager',
    budget: 1500,
    photos: ['https://picsum.photos/400/500?random=20'],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Potrero Hill',
      moveInDate: '2025-02-18',
      bedrooms: 2,
    },
    compatibility: 89,
  },
];

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Apartment',
    price: 2400,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    address: '123 Main St',
    city: 'San Francisco',
    state: 'CA',
    photos: ['https://picsum.photos/800/600?random=10'],
    amenities: ['Gym', 'Pool', 'Parking', 'Laundry'],
    description: 'Beautiful modern apartment in the heart of downtown with stunning city views.',
    available: true,
    hostId: 'host1',
    hostName: 'John Smith',
  },
  {
    id: '2',
    title: 'Cozy Suburban House',
    price: 1800,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    address: '456 Oak Ave',
    city: 'San Francisco',
    state: 'CA',
    photos: ['https://picsum.photos/800/600?random=11'],
    amenities: ['Backyard', 'Garage', 'Fireplace'],
    description: 'Quiet neighborhood, perfect for professionals. Pet-friendly with large backyard.',
    available: true,
    hostId: 'host2',
    hostName: 'Lisa Williams',
  },
];

export const mockGroups: Group[] = [
  {
    id: '1',
    name: 'Tech Professionals',
    description: 'Software engineers and tech workers looking for a place near Silicon Valley',
    members: ['1', '2'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2800,
    preferredLocation: 'Downtown',
    createdAt: new Date('2024-01-15'),
    createdBy: '1',
  },
  {
    id: '2',
    name: 'Creative Roommates',
    description: 'Artists, designers, and creative professionals seeking a collaborative living space',
    members: ['3'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2000,
    preferredLocation: 'Westside',
    createdAt: new Date('2024-01-20'),
    createdBy: '3',
  },
  {
    id: '3',
    name: 'Fitness Enthusiasts',
    description: 'Active lifestyle seekers who enjoy morning runs, gym sessions, and healthy living',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2200,
    preferredLocation: 'Marina District',
    createdAt: new Date('2024-02-01'),
    createdBy: '4',
  },
  {
    id: '4',
    name: 'Graduate Students',
    description: 'Grad students looking for a quiet, study-friendly environment near campus',
    members: ['5'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1600,
    preferredLocation: 'University Area',
    createdAt: new Date('2024-02-05'),
    createdBy: '5',
  },
  {
    id: '5',
    name: 'Young Professionals',
    description: 'Career-focused individuals in their 20s-30s seeking a social yet professional living space',
    members: [],
    pendingMembers: [],
    maxMembers: 5,
    budget: 2500,
    preferredLocation: 'Financial District',
    createdAt: new Date('2024-02-10'),
    createdBy: '6',
  },
  {
    id: '6',
    name: 'Pet Lovers',
    description: 'Dog and cat owners looking for a pet-friendly home with a yard',
    members: ['7'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2100,
    preferredLocation: 'Sunset District',
    createdAt: new Date('2024-02-12'),
    createdBy: '7',
  },
  {
    id: '7',
    name: 'Remote Workers',
    description: 'Digital nomads and remote workers seeking a home office-friendly space',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2400,
    preferredLocation: 'Mission District',
    createdAt: new Date('2024-02-15'),
    createdBy: '8',
  },
  {
    id: '8',
    name: 'Eco-Conscious Living',
    description: 'Environmentally conscious individuals committed to sustainable living practices',
    members: [],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1900,
    preferredLocation: 'Noe Valley',
    createdAt: new Date('2024-02-18'),
    createdBy: '9',
  },
  {
    id: '9',
    name: 'Music & Arts',
    description: 'Musicians, performers, and artists looking for a creative and soundproof space',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2300,
    preferredLocation: 'SOMA',
    createdAt: new Date('2024-02-20'),
    createdBy: '10',
  },
  {
    id: '10',
    name: 'Budget Conscious',
    description: 'Affordable living for those looking to save money while still enjoying good company',
    members: [],
    pendingMembers: [],
    maxMembers: 5,
    budget: 1400,
    preferredLocation: 'Richmond District',
    createdAt: new Date('2024-02-22'),
    createdBy: '11',
  },
  {
    id: '11',
    name: 'Early Risers',
    description: 'Morning people who enjoy sunrise workouts, coffee runs, and productive starts to the day',
    members: ['12'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2000,
    preferredLocation: 'Marina District',
    createdAt: new Date('2024-03-01'),
    createdBy: '12',
  },
  {
    id: '12',
    name: 'Night Owls',
    description: 'Late night workers and creative souls who thrive after dark',
    members: ['10'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1800,
    preferredLocation: 'Mission District',
    createdAt: new Date('2024-03-03'),
    createdBy: '10',
  },
  {
    id: '13',
    name: 'Healthcare Heroes',
    description: 'Nurses, doctors, and healthcare professionals with understanding of shift work',
    members: ['13'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2200,
    preferredLocation: 'Outer Sunset',
    createdAt: new Date('2024-03-05'),
    createdBy: '13',
  },
  {
    id: '14',
    name: 'Food Enthusiasts',
    description: 'Love cooking, sharing meals, and exploring new restaurants together',
    members: ['18'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2100,
    preferredLocation: 'North Beach',
    createdAt: new Date('2024-03-08'),
    createdBy: '18',
  },
  {
    id: '15',
    name: 'Minimalist Living',
    description: 'Simple, clutter-free lifestyle with focus on experiences over possessions',
    members: [],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1700,
    preferredLocation: 'Inner Sunset',
    createdAt: new Date('2024-03-10'),
    createdBy: '9',
  },
  {
    id: '16',
    name: 'Weekend Warriors',
    description: 'Adventure seekers who love hiking, biking, and outdoor weekend trips',
    members: ['6'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2300,
    preferredLocation: 'Castro',
    createdAt: new Date('2024-03-12'),
    createdBy: '14',
  },
  {
    id: '17',
    name: 'Book Club Roommates',
    description: 'Avid readers looking for quiet evenings and literary discussions',
    members: ['15', '19'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1900,
    preferredLocation: 'Pacific Heights',
    createdAt: new Date('2024-03-15'),
    createdBy: '15',
  },
  {
    id: '18',
    name: 'Gaming Community',
    description: 'Gamers and streamers looking for high-speed internet and gaming-friendly space',
    members: ['16'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1600,
    preferredLocation: 'SoMa',
    createdAt: new Date('2024-03-18'),
    createdBy: '16',
  },
  {
    id: '19',
    name: 'Yoga & Wellness',
    description: 'Mindful living with yoga practice, meditation, and holistic health focus',
    members: ['17'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2000,
    preferredLocation: 'Hayes Valley',
    createdAt: new Date('2024-03-20'),
    createdBy: '17',
  },
  {
    id: '20',
    name: 'Board Game Nights',
    description: 'Weekly game nights, friendly competition, and social gatherings',
    members: ['20'],
    pendingMembers: [],
    maxMembers: 5,
    budget: 2200,
    preferredLocation: 'Potrero Hill',
    createdAt: new Date('2024-03-22'),
    createdBy: '20',
  },
  {
    id: '21',
    name: 'Coffee Lovers',
    description: 'Morning coffee rituals, cafe hopping, and latte art appreciation',
    members: ['8'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1750,
    preferredLocation: 'Mission District',
    createdAt: new Date('2024-03-25'),
    createdBy: '8',
  },
  {
    id: '22',
    name: 'Language Exchange',
    description: 'Multilingual group practicing different languages and cultural exchange',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1850,
    preferredLocation: 'North Beach',
    createdAt: new Date('2024-03-28'),
    createdBy: '3',
  },
  {
    id: '23',
    name: 'Plant Parents',
    description: 'Green thumbs and plant collectors creating an urban jungle together',
    members: ['3', '17'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1650,
    preferredLocation: 'Noe Valley',
    createdAt: new Date('2024-04-01'),
    createdBy: '3',
  },
  {
    id: '24',
    name: 'Film Buffs',
    description: 'Movie enthusiasts who love cinema nights and film discussions',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1900,
    preferredLocation: 'Castro',
    createdAt: new Date('2024-04-03'),
    createdBy: '14',
  },
  {
    id: '25',
    name: 'Clean Freaks',
    description: 'Cleanliness is non-negotiable. Organized, tidy, and spotless living',
    members: ['1', '13', '15'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2400,
    preferredLocation: 'Pacific Heights',
    createdAt: new Date('2024-04-05'),
    createdBy: '1',
  },
];

export const mockConversations: Conversation[] = [
  {
    id: '1',
    participant: {
      id: '1',
      name: 'Sarah Johnson',
      photo: 'https://picsum.photos/100/100?random=1',
      online: true,
    },
    lastMessage: 'That sounds great! When can we schedule a viewing?',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    unread: 2,
  },
  {
    id: '2',
    participant: {
      id: '2',
      name: 'Michael Chen',
      photo: 'https://picsum.photos/100/100?random=2',
      online: false,
    },
    lastMessage: 'Thanks for reaching out!',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    unread: 0,
  },
];

export const mockApplications: Application[] = [
  {
    id: '1',
    propertyId: '1',
    propertyTitle: 'Modern Downtown Apartment',
    applicantId: 'renter1',
    applicantName: 'Sarah Johnson',
    applicantPhoto: 'https://picsum.photos/100/100?random=1',
    status: 'pending',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    message: 'I am very interested in this property. I work as a software engineer and can provide references.',
  },
  {
    id: '2',
    propertyId: '2',
    propertyTitle: 'Cozy Suburban House',
    applicantId: 'renter2',
    applicantName: 'Michael Chen',
    applicantPhoto: 'https://picsum.photos/100/100?random=2',
    status: 'pending',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24),
    message: 'This looks perfect for my needs. I have a stable job and excellent credit.',
  },
];
