import { RoommateProfile, Property, Group, Conversation, Application, User } from '../types/models';
import { getCityFromNeighborhood, getStateFromNeighborhood, getCoordinatesFromNeighborhood } from './locationData';

export const MOCK_DATA_VERSION = '1.6.0';

export const mockProfileUsers: User[] = [
  {
    id: '1',
    email: 'sarah.johnson@email.com',
    name: 'Sarah Johnson',
    age: 28,
    zodiacSign: 'Virgo',
    role: 'renter',
    profilePicture: 'https://picsum.photos/400/500?random=1',
    photos: [
      'https://picsum.photos/400/500?random=1',
      'https://picsum.photos/400/500?random=11',
      'https://picsum.photos/400/500?random=12',
    ],
    subscription: { plan: 'elite', status: 'active' },
    boostData: { boostsUsed: 2, isBoosted: true, boostExpiresAt: new Date(Date.now() + 20 * 60 * 60 * 1000), lastBoostDate: new Date() },
    profileData: {
      bio: 'Software engineer who loves hiking, cooking, and quiet evenings. Looking for a clean and respectful roommate.',
      budget: 1200,
      location: 'Downtown',
      neighborhood: 'Williamsburg',
      city: getCityFromNeighborhood('Williamsburg') || undefined,
      state: getStateFromNeighborhood('Williamsburg') || undefined,
      coordinates: getCoordinatesFromNeighborhood('Williamsburg') || undefined,
      occupation: 'Software Engineer',
      interests: 'hiking, cooking, reading',
      gender: 'female' as const,
      preferences: {
        sleepSchedule: 'early_sleeper',
        cleanliness: 'very_tidy',
        guestPolicy: 'rarely',
        noiseTolerance: 'prefer_quiet',
        smoking: 'no',
        workLocation: 'hybrid',
        roommateRelationship: 'respectful_coliving',
        pets: 'no_pets',
        lifestyle: ['active_gym', 'professional_focused', 'quiet_introverted'],
        sharedExpenses: { utilities: 'split_equally', groceries: 'buy_own', internet: 'split_equally', cleaning: 'take_turns' },
      },
    },
  },
  {
    id: '2',
    email: 'michael.chen@email.com',
    name: 'Michael Chen',
    age: 31,
    zodiacSign: 'Leo',
    role: 'renter',
    profilePicture: 'https://picsum.photos/400/500?random=2',
    photos: [
      'https://picsum.photos/400/500?random=2',
      'https://picsum.photos/400/500?random=21',
      'https://picsum.photos/400/500?random=22',
      'https://picsum.photos/400/500?random=23',
    ],
    subscription: { plan: 'plus', status: 'active' },
    boostData: { boostsUsed: 1, isBoosted: true, boostExpiresAt: new Date(Date.now() + 10 * 60 * 60 * 1000), lastBoostDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) },
    profileData: {
      bio: 'Marketing professional, gym enthusiast, and weekend adventurer. Love to host small gatherings!',
      budget: 1400,
      location: 'Midtown',
      neighborhood: 'Bushwick',
      city: getCityFromNeighborhood('Bushwick') || undefined,
      state: getStateFromNeighborhood('Bushwick') || undefined,
      coordinates: getCoordinatesFromNeighborhood('Bushwick') || undefined,
      occupation: 'Marketing Manager',
      interests: 'fitness, social events, traveling',
      gender: 'male' as const,
      preferences: {
        sleepSchedule: 'late_sleeper',
        cleanliness: 'moderately_tidy',
        guestPolicy: 'frequently',
        noiseTolerance: 'loud_environments',
        smoking: 'no',
        workLocation: 'office_fulltime',
        roommateRelationship: 'prefer_friends',
        pets: 'open_to_pets',
        lifestyle: ['active_gym', 'nightlife_social', 'professional_focused'],
        sharedExpenses: { utilities: 'split_equally', groceries: 'split_equally', internet: 'split_equally', cleaning: 'hire_cleaner' },
      },
    },
  },
  {
    id: '3',
    email: 'emily.rodriguez@email.com',
    name: 'Emily Rodriguez',
    age: 26,
    zodiacSign: 'Pisces',
    role: 'renter',
    profilePicture: 'https://picsum.photos/400/500?random=3',
    photos: [
      'https://picsum.photos/400/500?random=3',
      'https://picsum.photos/400/500?random=31',
      'https://picsum.photos/400/500?random=32',
      'https://picsum.photos/400/500?random=33',
      'https://picsum.photos/400/500?random=34',
    ],
    subscription: { plan: 'basic', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
    profileData: {
      bio: 'Graphic designer working from home. Cat mom, plant lover, and yoga enthusiast.',
      budget: 1000,
      location: 'Westside',
      neighborhood: 'Park Slope',
      city: getCityFromNeighborhood('Park Slope') || undefined,
      state: getStateFromNeighborhood('Park Slope') || undefined,
      coordinates: getCoordinatesFromNeighborhood('Park Slope') || undefined,
      occupation: 'Graphic Designer',
      interests: 'yoga, plants, cats, design',
      gender: 'female' as const,
      preferences: {
        sleepSchedule: 'flexible',
        cleanliness: 'moderately_tidy',
        guestPolicy: 'occasionally',
        noiseTolerance: 'normal_noise',
        smoking: 'no',
        workLocation: 'wfh_fulltime',
        roommateRelationship: 'occasional_hangouts',
        pets: 'have_pets',
        lifestyle: ['creative_artistic', 'quiet_introverted', 'homebody'],
      },
    },
  },
  {
    id: '4',
    email: 'bob.anderson@email.com',
    name: 'Bob Anderson',
    age: 27,
    zodiacSign: 'Taurus',
    role: 'renter',
    profilePicture: 'https://picsum.photos/400/500?random=4',
    photos: [
      'https://picsum.photos/400/500?random=4',
      'https://picsum.photos/400/500?random=41',
      'https://picsum.photos/400/500?random=42',
      'https://picsum.photos/400/500?random=43',
    ],
    subscription: { plan: 'elite', status: 'active' },
    boostData: { boostsUsed: 5, isBoosted: false },
    profileData: {
      bio: 'Teacher by day, musician by night. Looking for a chill roommate who appreciates good music and great conversations.',
      budget: 1100,
      location: 'Downtown',
      neighborhood: 'Astoria',
      city: getCityFromNeighborhood('Astoria') || undefined,
      state: getStateFromNeighborhood('Astoria') || undefined,
      coordinates: getCoordinatesFromNeighborhood('Astoria') || undefined,
      occupation: 'High School Teacher',
      interests: 'music, teaching, coffee shops',
      gender: 'male' as const,
      preferences: {
        sleepSchedule: 'flexible',
        cleanliness: 'moderately_tidy',
        guestPolicy: 'occasionally',
        noiseTolerance: 'normal_noise',
        smoking: 'no',
        workLocation: 'office_fulltime',
        roommateRelationship: 'occasional_hangouts',
        pets: 'no_pets',
        lifestyle: ['creative_artistic', 'professional_focused'],
      },
    },
  },
  {
    id: '5',
    email: 'jessica.park@email.com',
    name: 'Jessica Park',
    age: 25,
    zodiacSign: 'Cancer',
    role: 'renter',
    profilePicture: 'https://picsum.photos/400/500?random=5',
    photos: [
      'https://picsum.photos/400/500?random=5',
      'https://picsum.photos/400/500?random=51',
      'https://picsum.photos/400/500?random=52',
      'https://picsum.photos/400/500?random=53',
      'https://picsum.photos/400/500?random=54',
      'https://picsum.photos/400/500?random=55',
    ],
    subscription: { plan: 'plus', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
    profileData: {
      bio: 'Nurse working night shifts. Love yoga and meditation. Seeking a quiet, respectful living space.',
      budget: 950,
      location: 'Westside',
      neighborhood: 'Bushwick',
      city: getCityFromNeighborhood('Bushwick') || undefined,
      state: getStateFromNeighborhood('Bushwick') || undefined,
      coordinates: getCoordinatesFromNeighborhood('Bushwick') || undefined,
      occupation: 'Registered Nurse',
      interests: 'yoga, meditation, wellness',
      gender: 'female' as const,
      preferences: {
        sleepSchedule: 'irregular',
        cleanliness: 'very_tidy',
        guestPolicy: 'rarely',
        noiseTolerance: 'prefer_quiet',
        smoking: 'no',
        workLocation: 'irregular',
        roommateRelationship: 'respectful_coliving',
        pets: 'open_to_pets',
        lifestyle: ['active_gym', 'quiet_introverted'],
      },
    },
  },
  {
    id: '6',
    email: 'david.martinez@email.com',
    name: 'David Martinez',
    age: 29,
    zodiacSign: 'Capricorn',
    role: 'renter',
    profilePicture: 'https://picsum.photos/400/500?random=6',
    photos: [
      'https://picsum.photos/400/500?random=6',
      'https://picsum.photos/400/500?random=61',
      'https://picsum.photos/400/500?random=62',
    ],
    subscription: { plan: 'basic', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
    profileData: {
      bio: 'College student studying engineering. Easy-going, budget-conscious, and love gaming with friends.',
      budget: 800,
      location: 'University District',
      neighborhood: 'Astoria',
      city: getCityFromNeighborhood('Astoria') || undefined,
      state: getStateFromNeighborhood('Astoria') || undefined,
      coordinates: getCoordinatesFromNeighborhood('Astoria') || undefined,
      occupation: 'Student',
      interests: 'gaming, studying, basketball',
      gender: 'male' as const,
      preferences: {
        sleepSchedule: 'late_sleeper',
        cleanliness: 'moderately_tidy',
        guestPolicy: 'frequently',
        pets: 'no_pets',
        smoking: 'no',
        workLocation: 'office_fulltime',
        roommateRelationship: 'occasional_hangouts',
        noiseTolerance: 'loud_environments',
        lifestyle: ['nightlife_social'],
      },
    },
  },
  {
    id: '7',
    email: 'lisa.thompson@email.com',
    name: 'Lisa Thompson',
    age: 24,
    zodiacSign: 'Aries',
    role: 'renter',
    profilePicture: 'https://picsum.photos/400/500?random=7',
    photos: [
      'https://picsum.photos/400/500?random=7',
      'https://picsum.photos/400/500?random=71',
      'https://picsum.photos/400/500?random=72',
      'https://picsum.photos/400/500?random=73',
    ],
    subscription: { plan: 'plus', status: 'active' },
    boostData: { boostsUsed: 1, isBoosted: true, boostExpiresAt: new Date(Date.now() + 5 * 60 * 60 * 1000), lastBoostDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) },
    profileData: {
      bio: 'Veterinary assistant and dog lover. Looking for a pet-friendly home with outdoor space.',
      budget: 1050,
      location: 'Westside',
      neighborhood: 'Crown Heights',
      city: getCityFromNeighborhood('Crown Heights') || undefined,
      state: getStateFromNeighborhood('Crown Heights') || undefined,
      coordinates: getCoordinatesFromNeighborhood('Crown Heights') || undefined,
      occupation: 'Veterinary Assistant',
      interests: 'animals, hiking, outdoor activities',
      gender: 'female' as const,
      preferences: {
        sleepSchedule: 'early_sleeper',
        cleanliness: 'moderately_tidy',
        guestPolicy: 'occasionally',
        pets: 'have_pets',
        smoking: 'no',
        workLocation: 'office_fulltime',
        roommateRelationship: 'occasional_hangouts',
        noiseTolerance: 'normal_noise',
        lifestyle: ['active_gym', 'homebody'],
      },
    },
  },
  {
    id: '8',
    email: 'james.wilson@email.com',
    name: 'James Wilson',
    age: 28,
    zodiacSign: 'Gemini',
    role: 'renter',
    profilePicture: 'https://picsum.photos/400/500?random=8',
    photos: [
      'https://picsum.photos/400/500?random=8',
      'https://picsum.photos/400/500?random=81',
      'https://picsum.photos/400/500?random=82',
      'https://picsum.photos/400/500?random=83',
      'https://picsum.photos/400/500?random=84',
    ],
    subscription: { plan: 'elite', status: 'active' },
    boostData: { boostsUsed: 3, isBoosted: false },
    profileData: {
      bio: 'Finance analyst. Clean, organized, and professional. Prefer a quiet home environment.',
      budget: 1600,
      location: 'Downtown',
      neighborhood: 'Financial District',
      city: getCityFromNeighborhood('Financial District') || undefined,
      state: getStateFromNeighborhood('Financial District') || undefined,
      coordinates: getCoordinatesFromNeighborhood('Financial District') || undefined,
      occupation: 'Financial Analyst',
      interests: 'finance, running, podcasts',
      gender: 'male' as const,
      preferences: {
        sleepSchedule: 'early_sleeper',
        cleanliness: 'very_tidy',
        guestPolicy: 'rarely',
        pets: 'no_pets',
        smoking: 'no',
        workLocation: 'office_fulltime',
        roommateRelationship: 'respectful_coliving',
        noiseTolerance: 'prefer_quiet',
        lifestyle: ['professional_focused', 'quiet_introverted'],
      },
    },
  },
  {
    id: '9',
    email: 'amanda.lee@email.com',
    name: 'Amanda Lee',
    role: 'renter',
    subscription: { plan: 'basic', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
  {
    id: '10',
    email: 'ryan.garcia@email.com',
    name: 'Ryan Garcia',
    role: 'renter',
    subscription: { plan: 'plus', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
  {
    id: '11',
    email: 'sophia.brown@email.com',
    name: 'Sophia Brown',
    role: 'renter',
    subscription: { plan: 'elite', status: 'active' },
    boostData: { boostsUsed: 4, isBoosted: true, boostExpiresAt: new Date(Date.now() + 15 * 60 * 60 * 1000), lastBoostDate: new Date() },
  },
  {
    id: '12',
    email: 'matthew.davis@email.com',
    name: 'Matthew Davis',
    role: 'renter',
    subscription: { plan: 'basic', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
  {
    id: '13',
    email: 'olivia.miller@email.com',
    name: 'Olivia Miller',
    role: 'renter',
    subscription: { plan: 'plus', status: 'active' },
    boostData: { boostsUsed: 1, isBoosted: false, lastBoostDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) },
  },
  {
    id: '14',
    email: 'daniel.moore@email.com',
    name: 'Daniel Moore',
    role: 'renter',
    subscription: { plan: 'elite', status: 'active' },
    boostData: { boostsUsed: 6, isBoosted: false },
  },
  {
    id: '15',
    email: 'emma.taylor@email.com',
    name: 'Emma Taylor',
    role: 'renter',
    subscription: { plan: 'basic', status: 'active' },
    boostData: { boostsUsed: 0, isBoosted: false },
  },
];

export const mockRoommateProfiles: RoommateProfile[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    age: 24,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Software engineer who loves hiking, cooking, and quiet evenings. Looking for a clean and respectful roommate.',
    occupation: 'Software Engineer',
    budget: 1200,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=1',
      'https://picsum.photos/400/500?random=11',
      'https://picsum.photos/400/500?random=12',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Financial District',
      moveInDate: '01/01/2025',
      bedrooms: 2,
    },
    compatibility: 92,
  },
  {
    id: '2',
    name: 'Michael Chen',
    age: 26,
    zodiacSign: 'Leo',
    gender: 'male',
    bio: 'Marketing professional, gym enthusiast, and weekend adventurer. Love to host small gatherings!',
    occupation: 'Marketing Manager',
    budget: 1400,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=2',
      'https://picsum.photos/400/500?random=21',
      'https://picsum.photos/400/500?random=22',
      'https://picsum.photos/400/500?random=23',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 9,
      workSchedule: 'Office',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Bushwick',
      moveInDate: '02/01/2025',
      bedrooms: 2,
    },
    compatibility: 85,
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    age: 23,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Graphic designer working from home. Cat mom, plant lover, and yoga enthusiast.',
    occupation: 'Graphic Designer',
    budget: 1000,
    lookingFor: 'room',
    photos: [
      'https://picsum.photos/400/500?random=3',
      'https://picsum.photos/400/500?random=31',
      'https://picsum.photos/400/500?random=32',
      'https://picsum.photos/400/500?random=33',
      'https://picsum.photos/400/500?random=34',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Park Slope',
      moveInDate: '01/15/2025',
      bedrooms: 2,
    },
    compatibility: 78,
  },
  {
    id: '4',
    name: 'Bob Anderson',
    age: 27,
    zodiacSign: 'Taurus',
    gender: 'male',
    bio: 'Teacher by day, musician by night. Looking for a chill roommate who appreciates good music and great conversations.',
    occupation: 'High School Teacher',
    budget: 1100,
    lookingFor: 'entire_apartment',
    photos: [
      'https://picsum.photos/400/500?random=4',
      'https://picsum.photos/400/500?random=41',
      'https://picsum.photos/400/500?random=42',
      'https://picsum.photos/400/500?random=43',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Astoria',
      moveInDate: '01/10/2025',
      bedrooms: 2,
    },
    compatibility: 88,
  },
  {
    id: '5',
    name: 'Jessica Park',
    age: 25,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Data analyst with a passion for reading and meditation. Enjoys peaceful mornings and weekend brunches.',
    occupation: 'Data Analyst',
    budget: 1300,
    photos: [
      'https://picsum.photos/400/500?random=5',
      'https://picsum.photos/400/500?random=51',
      'https://picsum.photos/400/500?random=52',
      'https://picsum.photos/400/500?random=53',
      'https://picsum.photos/400/500?random=54',
      'https://picsum.photos/400/500?random=55',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 4,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Williamsburg',
      moveInDate: '01/20/2025',
      bedrooms: 1,
    },
    compatibility: 81,
  },
  {
    id: '6',
    name: 'David Martinez',
    age: 29,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Finance professional who loves running, cooking, and trying new restaurants. Early riser and weekend explorer.',
    occupation: 'Financial Analyst',
    budget: 1600,
    photos: [
      'https://picsum.photos/400/500?random=6',
      'https://picsum.photos/400/500?random=61',
      'https://picsum.photos/400/500?random=62',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Financial District',
      moveInDate: '02/15/2025',
      bedrooms: 2,
    },
    compatibility: 90,
  },
  {
    id: '7',
    name: 'Amanda White',
    age: 24,
    zodiacSign: 'Aries',
    gender: 'female',
    bio: 'Veterinary assistant and dog lover. Looking for a pet-friendly home with outdoor space.',
    occupation: 'Veterinary Assistant',
    budget: 1050,
    photos: [
      'https://picsum.photos/400/500?random=7',
      'https://picsum.photos/400/500?random=71',
      'https://picsum.photos/400/500?random=72',
      'https://picsum.photos/400/500?random=73',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Crown Heights',
      moveInDate: '01/25/2025',
      bedrooms: 2,
    },
    compatibility: 76,
  },
  {
    id: '8',
    name: 'Ryan Thompson',
    age: 28,
    zodiacSign: 'Gemini',
    gender: 'male',
    bio: 'Web developer working remotely. Coffee enthusiast, gamer, and tech geek. Quiet and focused during work hours.',
    occupation: 'Web Developer',
    budget: 1250,
    photos: [
      'https://picsum.photos/400/500?random=8',
      'https://picsum.photos/400/500?random=81',
      'https://picsum.photos/400/500?random=82',
      'https://picsum.photos/400/500?random=83',
      'https://picsum.photos/400/500?random=84',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 5,
      workSchedule: 'Remote',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Bushwick',
      moveInDate: '02/01/2025',
      bedrooms: 1,
    },
    compatibility: 83,
  },
  {
    id: '9',
    name: 'Olivia Green',
    age: 26,
    zodiacSign: 'Aquarius',
    gender: 'other',
    bio: 'Environmental scientist passionate about sustainability. Vegan, minimalist, and nature lover.',
    occupation: 'Environmental Scientist',
    budget: 950,
    photos: [
      'https://picsum.photos/400/500?random=9',
      'https://picsum.photos/400/500?random=91',
      'https://picsum.photos/400/500?random=92',
      'https://picsum.photos/400/500?random=93',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Park Slope',
      moveInDate: '01/30/2025',
      bedrooms: 2,
    },
    compatibility: 79,
  },
  {
    id: '10',
    name: 'James Lee',
    age: 30,
    zodiacSign: 'Sagittarius',
    gender: 'male',
    bio: 'Music producer and DJ. Night owl who loves creative projects and collaborative energy.',
    occupation: 'Music Producer',
    budget: 1150,
    photos: [
      'https://picsum.photos/400/500?random=10',
      'https://picsum.photos/400/500?random=101',
      'https://picsum.photos/400/500?random=102',
      'https://picsum.photos/400/500?random=103',
      'https://picsum.photos/400/500?random=104',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 8,
      workSchedule: 'Freelance',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Tribeca',
      moveInDate: '02/10/2025',
      bedrooms: 2,
    },
    compatibility: 72,
  },
  {
    id: '11',
    name: 'Sophia Kim',
    age: 22,
    zodiacSign: 'Libra',
    gender: 'female',
    bio: 'Graduate student studying architecture. Looking for quiet study space and friendly conversation.',
    occupation: 'Graduate Student',
    budget: 800,
    photos: [
      'https://picsum.photos/400/500?random=11',
      'https://picsum.photos/400/500?random=111',
      'https://picsum.photos/400/500?random=112',
      'https://picsum.photos/400/500?random=113',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 5,
      workSchedule: 'Student',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Upper East Side',
      moveInDate: '01/05/2025',
      bedrooms: 1,
    },
    compatibility: 85,
  },
  {
    id: '12',
    name: 'Marcus Johnson',
    age: 31,
    zodiacSign: 'Scorpio',
    gender: 'male',
    bio: 'Personal trainer and nutrition coach. Active lifestyle, early bird, and meal prep enthusiast.',
    occupation: 'Personal Trainer',
    budget: 1200,
    photos: [
      'https://picsum.photos/400/500?random=12',
      'https://picsum.photos/400/500?random=121',
      'https://picsum.photos/400/500?random=122',
      'https://picsum.photos/400/500?random=123',
      'https://picsum.photos/400/500?random=124',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Flexible',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Greenwich Village',
      moveInDate: '02/20/2025',
      bedrooms: 2,
    },
    compatibility: 87,
  },
  {
    id: '13',
    name: 'Isabella Garcia',
    age: 25,
    zodiacSign: 'Virgo',
    gender: 'female',
    bio: 'Nurse working rotating shifts. Looking for understanding roommate who respects varied schedules.',
    occupation: 'Registered Nurse',
    budget: 1100,
    photos: [
      'https://picsum.photos/400/500?random=13',
      'https://picsum.photos/400/500?random=131',
      'https://picsum.photos/400/500?random=132',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 6,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'East Williamsburg',
      moveInDate: '01/15/2025',
      bedrooms: 2,
    },
    compatibility: 82,
  },
  {
    id: '14',
    name: 'Alex Turner',
    age: 27,
    zodiacSign: 'Leo',
    gender: 'other',
    bio: 'Freelance photographer and travel blogger. Adventurous spirit looking for creative and open-minded roommate.',
    occupation: 'Photographer',
    budget: 1000,
    photos: [
      'https://picsum.photos/400/500?random=14',
      'https://picsum.photos/400/500?random=141',
      'https://picsum.photos/400/500?random=142',
      'https://picsum.photos/400/500?random=143',
      'https://picsum.photos/400/500?random=144',
      'https://picsum.photos/400/500?random=145',
    ],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 8,
      workSchedule: 'Freelance',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Chelsea',
      moveInDate: '02/05/2025',
      bedrooms: 1,
    },
    compatibility: 80,
  },
  {
    id: '15',
    name: 'Rachel Cohen',
    age: 29,
    zodiacSign: 'Pisces',
    gender: 'female',
    bio: 'Attorney with a busy schedule but loves to unwind with wine and good books. Organized and respectful.',
    occupation: 'Attorney',
    budget: 1700,
    photos: [
      'https://picsum.photos/400/500?random=15',
      'https://picsum.photos/400/500?random=151',
      'https://picsum.photos/400/500?random=152',
      'https://picsum.photos/400/500?random=153',
    ],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 5,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Upper West Side',
      moveInDate: '03/01/2025',
      bedrooms: 2,
    },
    compatibility: 91,
  },
  {
    id: '16',
    name: 'Kevin Patel',
    age: 23,
    zodiacSign: 'Taurus',
    gender: 'male',
    bio: 'Software engineering intern learning and growing. Gamer, coder, and pizza connoisseur.',
    occupation: 'Software Engineering Intern',
    budget: 900,
    photos: [
      'https://picsum.photos/400/500?random=16',
      'https://picsum.photos/400/500?random=161',
      'https://picsum.photos/400/500?random=162',
      'https://picsum.photos/400/500?random=163',
      'https://picsum.photos/400/500?random=164',
    ],
    lifestyle: {
      cleanliness: 6,
      socialLevel: 6,
      workSchedule: 'Office',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'SoHo',
      moveInDate: '01/12/2025',
      bedrooms: 1,
    },
    compatibility: 77,
  },
  {
    id: '17',
    name: 'Maya Williams',
    age: 26,
    zodiacSign: 'Cancer',
    gender: 'female',
    bio: 'Social media manager who works from cafes. Love plants, journaling, and afternoon yoga sessions.',
    occupation: 'Social Media Manager',
    budget: 1150,
    photos: [
      'https://picsum.photos/400/500?random=17',
      'https://picsum.photos/400/500?random=171',
      'https://picsum.photos/400/500?random=172',
    ],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Remote',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'East Village',
      moveInDate: '02/12/2025',
      bedrooms: 2,
    },
    compatibility: 84,
  },
  {
    id: '18',
    name: 'Chris Davis',
    age: 32,
    zodiacSign: 'Capricorn',
    gender: 'male',
    bio: 'Chef with irregular hours. Passionate about cooking and sharing meals. Clean kitchen is a must!',
    occupation: 'Chef',
    budget: 1300,
    photos: ['https://picsum.photos/400/500?random=18'],
    lifestyle: {
      cleanliness: 9,
      socialLevel: 8,
      workSchedule: 'Shifts',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Hell\'s Kitchen',
      moveInDate: '01/28/2025',
      bedrooms: 2,
    },
    compatibility: 86,
  },
  {
    id: '19',
    name: 'Natalie Brown',
    age: 24,
    zodiacSign: 'Aries',
    gender: 'female',
    bio: 'Aspiring writer working on my first novel. Quiet, introverted, but enjoy meaningful conversations.',
    occupation: 'Barista',
    budget: 850,
    photos: ['https://picsum.photos/400/500?random=19'],
    lifestyle: {
      cleanliness: 7,
      socialLevel: 4,
      workSchedule: 'Shifts',
      pets: true,
      smoking: false,
    },
    preferences: {
      location: 'Bedford-Stuyvesant',
      moveInDate: '02/08/2025',
      bedrooms: 1,
    },
    compatibility: 75,
  },
  {
    id: '20',
    name: 'Daniel Scott',
    age: 28,
    zodiacSign: 'Gemini',
    gender: 'male',
    bio: 'Product manager in tech. Balanced lifestyle with work and play. Board game nights are my favorite!',
    occupation: 'Product Manager',
    budget: 1500,
    photos: ['https://picsum.photos/400/500?random=20'],
    lifestyle: {
      cleanliness: 8,
      socialLevel: 7,
      workSchedule: 'Hybrid',
      pets: false,
      smoking: false,
    },
    preferences: {
      location: 'Flushing',
      moveInDate: '02/18/2025',
      bedrooms: 2,
    },
    compatibility: 89,
  },
];

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Apartment',
    price: 2400,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    address: '123 Main St',
    city: getCityFromNeighborhood('Financial District') || 'New York',
    state: getStateFromNeighborhood('Financial District') || 'NY',
    neighborhood: 'Financial District',
    coordinates: getCoordinatesFromNeighborhood('Financial District') || undefined,
    photos: ['https://picsum.photos/800/600?random=10'],
    amenities: ['Gym', 'Pool', 'Parking', 'Laundry'],
    description: 'Beautiful modern apartment in the heart of downtown with stunning city views.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 98,
  },
  {
    id: '2',
    title: 'Cozy Suburban House - Room Available',
    price: 900,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    address: '456 Oak Ave',
    city: getCityFromNeighborhood('Williamsburg') || 'New York',
    state: getStateFromNeighborhood('Williamsburg') || 'NY',
    neighborhood: 'Williamsburg',
    coordinates: getCoordinatesFromNeighborhood('Williamsburg') || undefined,
    photos: ['https://picsum.photos/800/600?random=11'],
    amenities: ['Backyard', 'Garage', 'Fireplace'],
    description: 'Quiet neighborhood, perfect for professionals. Pet-friendly with large backyard. Female roommate already living there.',
    available: true,
    hostId: '1',
    hostName: 'Sarah Johnson',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'female', onApp: false },
    ],
    hostProfileId: '1',
    walkScore: 94,
  },
  {
    id: '3',
    title: 'Luxury Penthouse Suite',
    price: 3500,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2200,
    address: '789 Sky Tower',
    city: getCityFromNeighborhood('Tribeca') || 'New York',
    state: getStateFromNeighborhood('Tribeca') || 'NY',
    neighborhood: 'Tribeca',
    coordinates: getCoordinatesFromNeighborhood('Tribeca') || undefined,
    photos: ['https://picsum.photos/800/600?random=12'],
    amenities: ['Gym', 'Pool', 'Concierge', 'Parking', 'Rooftop Deck'],
    description: 'Stunning penthouse with panoramic city and bay views. Premium finishes throughout.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 97,
  },
  {
    id: '4',
    title: 'Charming Studio - Roommate Needed',
    price: 700,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    address: '234 Elm Street',
    city: getCityFromNeighborhood('Bushwick') || 'New York',
    state: getStateFromNeighborhood('Bushwick') || 'NY',
    neighborhood: 'Bushwick',
    coordinates: getCoordinatesFromNeighborhood('Bushwick') || undefined,
    photos: ['https://picsum.photos/800/600?random=13'],
    amenities: ['Laundry', 'Pet Friendly'],
    description: 'Cozy studio perfect for young professionals. Walk to public transit. Male roommate and female roommate already living there.',
    available: true,
    hostId: '2',
    hostName: 'Michael Chen',
    featured: false,
    propertyType: 'sublet',
    roomType: 'room',
    existingRoommates: [
      { gender: 'male', onApp: false },
      { gender: 'female', onApp: true, userId: '5' },
    ],
    hostProfileId: '2',
    walkScore: 88,
  },
  {
    id: '5',
    title: 'Spacious Family Home',
    price: 2800,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2000,
    address: '567 Maple Drive',
    city: getCityFromNeighborhood('Upper East Side') || 'New York',
    state: getStateFromNeighborhood('Upper East Side') || 'NY',
    neighborhood: 'Upper East Side',
    coordinates: getCoordinatesFromNeighborhood('Upper East Side') || undefined,
    photos: ['https://picsum.photos/800/600?random=14'],
    amenities: ['Backyard', 'Garage', 'Fireplace', 'Dishwasher'],
    description: 'Perfect family home in a quiet neighborhood with great schools nearby.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 91,
  },
  {
    id: '6',
    title: 'Urban Loft - Room Available',
    price: 1100,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    address: '890 Industrial Way',
    city: getCityFromNeighborhood('Park Slope') || 'New York',
    state: getStateFromNeighborhood('Park Slope') || 'NY',
    neighborhood: 'Park Slope',
    coordinates: getCoordinatesFromNeighborhood('Park Slope') || undefined,
    photos: ['https://picsum.photos/800/600?random=15'],
    amenities: ['Gym', 'Parking', 'Exposed Brick'],
    description: 'Trendy loft with high ceilings and modern industrial design. Female roommate already living there.',
    available: true,
    hostId: '3',
    hostName: 'Emily Rodriguez',
    featured: false,
    propertyType: 'sublet',
    roomType: 'room',
    existingRoommates: [
      { gender: 'female', onApp: false },
    ],
    hostProfileId: '3',
    walkScore: 93,
  },
  {
    id: '7',
    title: 'Sunny Chelsea Studio',
    price: 1800,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    address: '125 W 23rd St',
    city: getCityFromNeighborhood('Chelsea') || 'New York',
    state: getStateFromNeighborhood('Chelsea') || 'NY',
    neighborhood: 'Chelsea',
    coordinates: getCoordinatesFromNeighborhood('Chelsea') || undefined,
    photos: ['https://picsum.photos/800/600?random=16'],
    amenities: ['Doorman', 'Elevator', 'Laundry'],
    description: 'Bright studio with southern exposure in the heart of Chelsea. Walking distance to galleries and restaurants.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 96,
  },
  {
    id: '8',
    title: 'Astoria Shared Apartment',
    price: 850,
    bedrooms: 3,
    bathrooms: 1,
    sqft: 1000,
    address: '45 Broadway',
    city: getCityFromNeighborhood('Astoria') || 'New York',
    state: getStateFromNeighborhood('Astoria') || 'NY',
    neighborhood: 'Astoria',
    coordinates: getCoordinatesFromNeighborhood('Astoria') || undefined,
    photos: ['https://picsum.photos/800/600?random=17'],
    amenities: ['Laundry', 'Near Subway'],
    description: 'Affordable room in Queens with great subway access. Two roommates already living here.',
    available: true,
    hostId: '4',
    hostName: 'Bob Anderson',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'male', onApp: true, userId: '4' },
      { gender: 'female', onApp: false },
    ],
    hostProfileId: '4',
    walkScore: 90,
  },
  {
    id: '9',
    title: 'West Village Duplex',
    price: 4200,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    address: '88 Grove St',
    city: getCityFromNeighborhood('West Village') || 'New York',
    state: getStateFromNeighborhood('West Village') || 'NY',
    neighborhood: 'West Village',
    coordinates: getCoordinatesFromNeighborhood('West Village') || undefined,
    photos: ['https://picsum.photos/800/600?random=18'],
    amenities: ['Fireplace', 'Private Terrace', 'Washer/Dryer'],
    description: 'Charming two-level apartment on a tree-lined street. Steps from Washington Square Park.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 97,
  },
  {
    id: '10',
    title: 'LES Creative Space',
    price: 950,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 750,
    address: '156 Ludlow St',
    city: getCityFromNeighborhood('Lower East Side') || 'New York',
    state: getStateFromNeighborhood('Lower East Side') || 'NY',
    neighborhood: 'Lower East Side',
    coordinates: getCoordinatesFromNeighborhood('Lower East Side') || undefined,
    photos: ['https://picsum.photos/800/600?random=19'],
    amenities: ['Exposed Brick', 'High Ceilings'],
    description: 'Artistic space perfect for creatives. Male roommate already living here.',
    available: true,
    hostId: '6',
    hostName: 'Marcus Thompson',
    featured: false,
    propertyType: 'sublet',
    roomType: 'room',
    existingRoommates: [
      { gender: 'male', onApp: false },
    ],
    hostProfileId: '6',
    walkScore: 92,
  },
  {
    id: '11',
    title: 'Greenpoint Garden Apartment',
    price: 1300,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    address: '221 Franklin St',
    city: getCityFromNeighborhood('Greenpoint') || 'New York',
    state: getStateFromNeighborhood('Greenpoint') || 'NY',
    neighborhood: 'Greenpoint',
    coordinates: getCoordinatesFromNeighborhood('Greenpoint') || undefined,
    photos: ['https://picsum.photos/800/600?random=20'],
    amenities: ['Garden', 'Pet Friendly', 'Laundry'],
    description: 'Ground floor apartment with private garden access. Close to waterfront parks.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 93,
  },
  {
    id: '12',
    title: 'SoHo Loft Space',
    price: 3800,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1400,
    address: '77 Mercer St',
    city: getCityFromNeighborhood('SoHo') || 'New York',
    state: getStateFromNeighborhood('SoHo') || 'NY',
    neighborhood: 'SoHo',
    coordinates: getCoordinatesFromNeighborhood('SoHo') || undefined,
    photos: ['https://picsum.photos/800/600?random=21'],
    amenities: ['Exposed Brick', 'High Ceilings', 'Central AC'],
    description: 'Iconic SoHo loft with dramatic 14-foot ceilings and large windows.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: true,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 96,
  },
  {
    id: '13',
    title: 'Harlem Brownstone Room',
    price: 950,
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1800,
    address: '342 W 122nd St',
    city: getCityFromNeighborhood('Harlem') || 'New York',
    state: getStateFromNeighborhood('Harlem') || 'NY',
    neighborhood: 'Harlem',
    coordinates: getCoordinatesFromNeighborhood('Harlem') || undefined,
    photos: ['https://picsum.photos/800/600?random=22'],
    amenities: ['Original Details', 'Backyard', 'Fireplace'],
    description: 'Beautiful room in historic brownstone. Three other roommates, very social household.',
    available: true,
    hostId: '7',
    hostName: 'Jessica Williams',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'female', onApp: true, userId: '7' },
      { gender: 'male', onApp: false },
      { gender: 'female', onApp: false },
    ],
    hostProfileId: '7',
    walkScore: 89,
  },
  {
    id: '14',
    title: 'East Village Walk-Up',
    price: 1600,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    address: '88 St Marks Pl',
    city: getCityFromNeighborhood('East Village') || 'New York',
    state: getStateFromNeighborhood('East Village') || 'NY',
    neighborhood: 'East Village',
    coordinates: getCoordinatesFromNeighborhood('East Village') || undefined,
    photos: ['https://picsum.photos/800/600?random=23'],
    amenities: ['Exposed Brick', 'Near Subway'],
    description: 'Classic East Village studio on a vibrant block. 4th floor walk-up.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: false,
    propertyType: 'sublet',
    roomType: 'entire',
    walkScore: 95,
  },
  {
    id: '15',
    title: 'Battery Park City Modern',
    price: 2900,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    address: '99 Battery Pl',
    city: getCityFromNeighborhood('Battery Park City') || 'New York',
    state: getStateFromNeighborhood('Battery Park City') || 'NY',
    neighborhood: 'Battery Park City',
    coordinates: getCoordinatesFromNeighborhood('Battery Park City') || undefined,
    photos: ['https://picsum.photos/800/600?random=24'],
    amenities: ['Gym', 'Doorman', 'Pool', 'River Views'],
    description: 'Luxury living with stunning Hudson River views. Full amenity building.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 87,
  },
  {
    id: '16',
    title: 'Crown Heights Shared House',
    price: 800,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1200,
    address: '455 Eastern Pkwy',
    city: getCityFromNeighborhood('Crown Heights') || 'New York',
    state: getStateFromNeighborhood('Crown Heights') || 'NY',
    neighborhood: 'Crown Heights',
    coordinates: getCoordinatesFromNeighborhood('Crown Heights') || undefined,
    photos: ['https://picsum.photos/800/600?random=25'],
    amenities: ['Backyard', 'Laundry', 'Near Subway'],
    description: 'Spacious room in friendly house. Close to Prospect Park. Two roommates.',
    available: true,
    hostId: '8',
    hostName: 'Rachel Davis',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'female', onApp: true, userId: '8' },
      { gender: 'male', onApp: false },
    ],
    hostProfileId: '8',
    walkScore: 90,
  },
  {
    id: '17',
    title: 'Midtown Studio',
    price: 2100,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 450,
    address: '333 E 43rd St',
    city: getCityFromNeighborhood('Midtown East') || 'New York',
    state: getStateFromNeighborhood('Midtown East') || 'NY',
    neighborhood: 'Midtown East',
    coordinates: getCoordinatesFromNeighborhood('Midtown East') || undefined,
    photos: ['https://picsum.photos/800/600?random=26'],
    amenities: ['Doorman', 'Elevator', 'Laundry'],
    description: 'Efficient studio in prime Midtown location. Perfect for professionals.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 88,
  },
  {
    id: '18',
    title: 'Brooklyn Heights Townhouse',
    price: 1400,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2200,
    address: '78 Hicks St',
    city: getCityFromNeighborhood('Brooklyn Heights') || 'New York',
    state: getStateFromNeighborhood('Brooklyn Heights') || 'NY',
    neighborhood: 'Brooklyn Heights',
    coordinates: getCoordinatesFromNeighborhood('Brooklyn Heights') || undefined,
    photos: ['https://picsum.photos/800/600?random=27'],
    amenities: ['Garden', 'Fireplace', 'Original Details'],
    description: 'Beautiful room in historic townhouse. Close to promenade and subways.',
    available: true,
    hostId: '9',
    hostName: 'James Martinez',
    featured: false,
    propertyType: 'lease',
    roomType: 'room',
    existingRoommates: [
      { gender: 'male', onApp: false },
      { gender: 'male', onApp: false },
      { gender: 'female', onApp: true, userId: '9' },
    ],
    hostProfileId: '9',
    walkScore: 94,
  },
  {
    id: '19',
    title: 'Murray Hill High-Rise',
    price: 2500,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 950,
    address: '200 E 36th St',
    city: getCityFromNeighborhood('Murray Hill') || 'New York',
    state: getStateFromNeighborhood('Murray Hill') || 'NY',
    neighborhood: 'Murray Hill',
    coordinates: getCoordinatesFromNeighborhood('Murray Hill') || undefined,
    photos: ['https://picsum.photos/800/600?random=28'],
    amenities: ['Doorman', 'Gym', 'Laundry'],
    description: 'Modern apartment in full-service building. Great for commuters.',
    available: true,
    hostId: 'agent2',
    hostName: 'Elite Properties',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 89,
  },
  {
    id: '20',
    title: 'Prospect Heights Condo',
    price: 2200,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    address: '567 Dean St',
    city: getCityFromNeighborhood('Prospect Heights') || 'New York',
    state: getStateFromNeighborhood('Prospect Heights') || 'NY',
    neighborhood: 'Prospect Heights',
    coordinates: getCoordinatesFromNeighborhood('Prospect Heights') || undefined,
    photos: ['https://picsum.photos/800/600?random=29'],
    amenities: ['Laundry', 'Storage', 'Elevator'],
    description: 'Renovated condo near Barclays Center and Brooklyn Museum.',
    available: true,
    hostId: 'agent1',
    hostName: 'Premier Realty Group',
    featured: false,
    propertyType: 'lease',
    roomType: 'entire',
    walkScore: 91,
  },
];

export const mockGroups: Group[] = [
  {
    id: '1',
    name: 'Tech Professionals',
    description: 'Software engineers and tech workers looking for a place near Silicon Valley',
    members: ['1', '2'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2800,
    preferredLocation: 'Downtown',
    createdAt: new Date('2024-01-15'),
    createdBy: '1',
  },
  {
    id: '2',
    name: 'Creative Roommates',
    description: 'Artists, designers, and creative professionals seeking a collaborative living space',
    members: ['3'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2000,
    preferredLocation: 'Westside',
    createdAt: new Date('2024-01-20'),
    createdBy: '3',
  },
  {
    id: '3',
    name: 'Fitness Enthusiasts',
    description: 'Active lifestyle seekers who enjoy morning runs, gym sessions, and healthy living',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2200,
    preferredLocation: 'Marina District',
    createdAt: new Date('2024-02-01'),
    createdBy: '4',
  },
  {
    id: '4',
    name: 'Graduate Students',
    description: 'Grad students looking for a quiet, study-friendly environment near campus',
    members: ['5'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1600,
    preferredLocation: 'University Area',
    createdAt: new Date('2024-02-05'),
    createdBy: '5',
  },
  {
    id: '5',
    name: 'Young Professionals',
    description: 'Career-focused individuals in their 20s-30s seeking a social yet professional living space',
    members: [],
    pendingMembers: [],
    maxMembers: 5,
    budget: 2500,
    preferredLocation: 'Financial District',
    createdAt: new Date('2024-02-10'),
    createdBy: '6',
  },
  {
    id: '6',
    name: 'Pet Lovers',
    description: 'Dog and cat owners looking for a pet-friendly home with a yard',
    members: ['7'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2100,
    preferredLocation: 'Sunset District',
    createdAt: new Date('2024-02-12'),
    createdBy: '7',
  },
  {
    id: '7',
    name: 'Remote Workers',
    description: 'Digital nomads and remote workers seeking a home office-friendly space',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2400,
    preferredLocation: 'Mission District',
    createdAt: new Date('2024-02-15'),
    createdBy: '8',
  },
  {
    id: '8',
    name: 'Eco-Conscious Living',
    description: 'Environmentally conscious individuals committed to sustainable living practices',
    members: [],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1900,
    preferredLocation: 'Noe Valley',
    createdAt: new Date('2024-02-18'),
    createdBy: '9',
  },
  {
    id: '9',
    name: 'Music & Arts',
    description: 'Musicians, performers, and artists looking for a creative and soundproof space',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2300,
    preferredLocation: 'SOMA',
    createdAt: new Date('2024-02-20'),
    createdBy: '10',
  },
  {
    id: '10',
    name: 'Budget Conscious',
    description: 'Affordable living for those looking to save money while still enjoying good company',
    members: [],
    pendingMembers: [],
    maxMembers: 5,
    budget: 1400,
    preferredLocation: 'Richmond District',
    createdAt: new Date('2024-02-22'),
    createdBy: '11',
  },
  {
    id: '11',
    name: 'Early Risers',
    description: 'Morning people who enjoy sunrise workouts, coffee runs, and productive starts to the day',
    members: ['12'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2000,
    preferredLocation: 'Marina District',
    createdAt: new Date('2024-03-01'),
    createdBy: '12',
  },
  {
    id: '12',
    name: 'Night Owls',
    description: 'Late night workers and creative souls who thrive after dark',
    members: ['10'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1800,
    preferredLocation: 'Mission District',
    createdAt: new Date('2024-03-03'),
    createdBy: '10',
  },
  {
    id: '13',
    name: 'Healthcare Heroes',
    description: 'Nurses, doctors, and healthcare professionals with understanding of shift work',
    members: ['13'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2200,
    preferredLocation: 'Outer Sunset',
    createdAt: new Date('2024-03-05'),
    createdBy: '13',
  },
  {
    id: '14',
    name: 'Food Enthusiasts',
    description: 'Love cooking, sharing meals, and exploring new restaurants together',
    members: ['18'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2100,
    preferredLocation: 'North Beach',
    createdAt: new Date('2024-03-08'),
    createdBy: '18',
  },
  {
    id: '15',
    name: 'Minimalist Living',
    description: 'Simple, clutter-free lifestyle with focus on experiences over possessions',
    members: [],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1700,
    preferredLocation: 'Inner Sunset',
    createdAt: new Date('2024-03-10'),
    createdBy: '9',
  },
  {
    id: '16',
    name: 'Weekend Warriors',
    description: 'Adventure seekers who love hiking, biking, and outdoor weekend trips',
    members: ['6'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2300,
    preferredLocation: 'Castro',
    createdAt: new Date('2024-03-12'),
    createdBy: '14',
  },
  {
    id: '17',
    name: 'Book Club Roommates',
    description: 'Avid readers looking for quiet evenings and literary discussions',
    members: ['15', '19'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1900,
    preferredLocation: 'Pacific Heights',
    createdAt: new Date('2024-03-15'),
    createdBy: '15',
  },
  {
    id: '18',
    name: 'Gaming Community',
    description: 'Gamers and streamers looking for high-speed internet and gaming-friendly space',
    members: ['16'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1600,
    preferredLocation: 'SoMa',
    createdAt: new Date('2024-03-18'),
    createdBy: '16',
  },
  {
    id: '19',
    name: 'Yoga & Wellness',
    description: 'Mindful living with yoga practice, meditation, and holistic health focus',
    members: ['17'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 2000,
    preferredLocation: 'Hayes Valley',
    createdAt: new Date('2024-03-20'),
    createdBy: '17',
  },
  {
    id: '20',
    name: 'Board Game Nights',
    description: 'Weekly game nights, friendly competition, and social gatherings',
    members: ['20'],
    pendingMembers: [],
    maxMembers: 5,
    budget: 2200,
    preferredLocation: 'Potrero Hill',
    createdAt: new Date('2024-03-22'),
    createdBy: '20',
  },
  {
    id: '21',
    name: 'Coffee Lovers',
    description: 'Morning coffee rituals, cafe hopping, and latte art appreciation',
    members: ['8'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1750,
    preferredLocation: 'Mission District',
    createdAt: new Date('2024-03-25'),
    createdBy: '8',
  },
  {
    id: '22',
    name: 'Language Exchange',
    description: 'Multilingual group practicing different languages and cultural exchange',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1850,
    preferredLocation: 'North Beach',
    createdAt: new Date('2024-03-28'),
    createdBy: '3',
  },
  {
    id: '23',
    name: 'Plant Parents',
    description: 'Green thumbs and plant collectors creating an urban jungle together',
    members: ['3', '17'],
    pendingMembers: [],
    maxMembers: 3,
    budget: 1650,
    preferredLocation: 'Noe Valley',
    createdAt: new Date('2024-04-01'),
    createdBy: '3',
  },
  {
    id: '24',
    name: 'Film Buffs',
    description: 'Movie enthusiasts who love cinema nights and film discussions',
    members: [],
    pendingMembers: [],
    maxMembers: 4,
    budget: 1900,
    preferredLocation: 'Castro',
    createdAt: new Date('2024-04-03'),
    createdBy: '14',
  },
  {
    id: '25',
    name: 'Clean Freaks',
    description: 'Cleanliness is non-negotiable. Organized, tidy, and spotless living',
    members: ['1', '13', '15'],
    pendingMembers: [],
    maxMembers: 4,
    budget: 2400,
    preferredLocation: 'Pacific Heights',
    createdAt: new Date('2024-04-05'),
    createdBy: '1',
  },
];

export const mockConversations: Conversation[] = [
  {
    id: '1',
    participant: {
      id: '1',
      name: 'Sarah Johnson',
      photo: 'https://picsum.photos/100/100?random=1',
      online: true,
    },
    lastMessage: 'That sounds great! When can we schedule a viewing?',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    unread: 2,
    messages: [],
  },
  {
    id: '2',
    participant: {
      id: '2',
      name: 'Michael Chen',
      photo: 'https://picsum.photos/100/100?random=2',
      online: false,
    },
    lastMessage: 'Thanks for reaching out!',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    unread: 0,
    messages: [],
  },
];

export const mockApplications: Application[] = [
  {
    id: '1',
    propertyId: '1',
    propertyTitle: 'Modern Downtown Apartment',
    applicantId: 'renter1',
    applicantName: 'Sarah Johnson',
    applicantPhoto: 'https://picsum.photos/100/100?random=1',
    status: 'pending',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    message: 'I am very interested in this property. I work as a software engineer and can provide references.',
  },
  {
    id: '2',
    propertyId: '2',
    propertyTitle: 'Cozy Suburban House',
    applicantId: 'renter2',
    applicantName: 'Michael Chen',
    applicantPhoto: 'https://picsum.photos/100/100?random=2',
    status: 'pending',
    submittedDate: new Date(Date.now() - 1000 * 60 * 60 * 24),
    message: 'This looks perfect for my needs. I have a stable job and excellent credit.',
  },
];
